// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="bd_d92b_csc_0_v_csc,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu2cg-sfvc784-1-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=3.442875,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=4306,HLS_SYN_LUT=6102,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module bd_d92b_csc_0_v_csc (
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        s_axis_video_TDATA,
        s_axis_video_TKEEP,
        s_axis_video_TSTRB,
        s_axis_video_TUSER,
        s_axis_video_TLAST,
        s_axis_video_TID,
        s_axis_video_TDEST,
        m_axis_video_TDATA,
        m_axis_video_TKEEP,
        m_axis_video_TSTRB,
        m_axis_video_TUSER,
        m_axis_video_TLAST,
        m_axis_video_TID,
        m_axis_video_TDEST,
        s_axis_video_TVALID,
        s_axis_video_TREADY,
        m_axis_video_TVALID,
        m_axis_video_TREADY
);

parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 9;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
input  [47:0] s_axis_video_TDATA;
input  [5:0] s_axis_video_TKEEP;
input  [5:0] s_axis_video_TSTRB;
input  [0:0] s_axis_video_TUSER;
input  [0:0] s_axis_video_TLAST;
input  [0:0] s_axis_video_TID;
input  [0:0] s_axis_video_TDEST;
output  [47:0] m_axis_video_TDATA;
output  [5:0] m_axis_video_TKEEP;
output  [5:0] m_axis_video_TSTRB;
output  [0:0] m_axis_video_TUSER;
output  [0:0] m_axis_video_TLAST;
output  [0:0] m_axis_video_TID;
output  [0:0] m_axis_video_TDEST;
input   s_axis_video_TVALID;
output   s_axis_video_TREADY;
output   m_axis_video_TVALID;
input   m_axis_video_TREADY;

 reg    ap_rst_n_inv;
wire   [7:0] InVideoFormat;
wire   [7:0] OutVideoFormat;
wire   [15:0] width;
wire   [15:0] height;
wire   [15:0] ColStart;
wire   [15:0] ColEnd;
wire   [15:0] RowStart;
wire   [15:0] RowEnd;
wire   [15:0] K11;
wire   [15:0] K12;
wire   [15:0] K13;
wire   [15:0] K21;
wire   [15:0] K22;
wire   [15:0] K23;
wire   [15:0] K31;
wire   [15:0] K32;
wire   [15:0] K33;
wire   [9:0] ROffset;
wire   [9:0] GOffset;
wire   [9:0] BOffset;
wire   [7:0] ClampMin;
wire   [7:0] ClipMax;
wire   [15:0] K11_2;
wire   [15:0] K12_2;
wire   [15:0] K13_2;
wire   [15:0] K21_2;
wire   [15:0] K22_2;
wire   [15:0] K23_2;
wire   [15:0] K31_2;
wire   [15:0] K32_2;
wire   [15:0] K33_2;
wire   [9:0] ROffset_2;
wire   [9:0] GOffset_2;
wire   [9:0] BOffset_2;
wire   [7:0] ClampMin_2;
wire   [7:0] ClipMax_2;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire    Block_entry_proc_1_U0_ap_start;
wire    Block_entry_proc_1_U0_ap_done;
wire    Block_entry_proc_1_U0_ap_continue;
wire    Block_entry_proc_1_U0_ap_idle;
wire    Block_entry_proc_1_U0_ap_ready;
wire   [0:0] Block_entry_proc_1_U0_ap_return_0;
wire   [0:0] Block_entry_proc_1_U0_ap_return_1;
wire    ap_channel_done_cond64_loc_channel;
wire    cond64_loc_channel_full_n;
reg    ap_sync_reg_channel_write_cond64_loc_channel;
wire    ap_sync_channel_write_cond64_loc_channel;
wire    ap_channel_done_cond_loc_channel;
wire    cond_loc_channel_full_n;
reg    ap_sync_reg_channel_write_cond_loc_channel;
wire    ap_sync_channel_write_cond_loc_channel;
wire    AXIvideo2MultiPixStream_U0_ap_start;
wire    AXIvideo2MultiPixStream_U0_ap_done;
wire    AXIvideo2MultiPixStream_U0_ap_continue;
wire    AXIvideo2MultiPixStream_U0_ap_idle;
wire    AXIvideo2MultiPixStream_U0_ap_ready;
wire    AXIvideo2MultiPixStream_U0_s_axis_video_TREADY;
wire   [47:0] AXIvideo2MultiPixStream_U0_stream_in_din;
wire    AXIvideo2MultiPixStream_U0_stream_in_write;
wire    v_hcresampler_core_U0_ap_start;
wire    v_hcresampler_core_U0_ap_done;
wire    v_hcresampler_core_U0_ap_continue;
wire    v_hcresampler_core_U0_ap_idle;
wire    v_hcresampler_core_U0_ap_ready;
wire    v_hcresampler_core_U0_start_out;
wire    v_hcresampler_core_U0_start_write;
wire    v_hcresampler_core_U0_stream_in_read;
wire   [47:0] v_hcresampler_core_U0_stream_in_hresampled_din;
wire    v_hcresampler_core_U0_stream_in_hresampled_write;
wire   [31:0] v_hcresampler_core_U0_stream_in_hresampled_num_data_valid;
wire   [31:0] v_hcresampler_core_U0_stream_in_hresampled_fifo_cap;
wire    v_csc_core_U0_ap_start;
wire    v_csc_core_U0_ap_done;
wire    v_csc_core_U0_ap_continue;
wire    v_csc_core_U0_ap_idle;
wire    v_csc_core_U0_ap_ready;
wire    v_csc_core_U0_stream_in_hresampled_read;
wire   [47:0] v_csc_core_U0_stream_csc_din;
wire    v_csc_core_U0_stream_csc_write;
wire   [31:0] v_csc_core_U0_stream_csc_num_data_valid;
wire   [31:0] v_csc_core_U0_stream_csc_fifo_cap;
wire    v_hcresampler_core_1_U0_ap_start;
wire    v_hcresampler_core_1_U0_ap_done;
wire    v_hcresampler_core_1_U0_ap_continue;
wire    v_hcresampler_core_1_U0_ap_idle;
wire    v_hcresampler_core_1_U0_ap_ready;
wire    v_hcresampler_core_1_U0_start_out;
wire    v_hcresampler_core_1_U0_start_write;
wire    v_hcresampler_core_1_U0_stream_csc_read;
wire   [47:0] v_hcresampler_core_1_U0_stream_out_hresampled_din;
wire    v_hcresampler_core_1_U0_stream_out_hresampled_write;
wire   [31:0] v_hcresampler_core_1_U0_stream_out_hresampled_num_data_valid;
wire   [31:0] v_hcresampler_core_1_U0_stream_out_hresampled_fifo_cap;
wire    MultiPixStream2AXIvideo_U0_ap_start;
wire    MultiPixStream2AXIvideo_U0_ap_done;
wire    MultiPixStream2AXIvideo_U0_ap_continue;
wire    MultiPixStream2AXIvideo_U0_ap_idle;
wire    MultiPixStream2AXIvideo_U0_ap_ready;
wire    MultiPixStream2AXIvideo_U0_stream_out_hresampled_read;
wire   [47:0] MultiPixStream2AXIvideo_U0_m_axis_video_TDATA;
wire    MultiPixStream2AXIvideo_U0_m_axis_video_TVALID;
wire   [5:0] MultiPixStream2AXIvideo_U0_m_axis_video_TKEEP;
wire   [5:0] MultiPixStream2AXIvideo_U0_m_axis_video_TSTRB;
wire   [0:0] MultiPixStream2AXIvideo_U0_m_axis_video_TUSER;
wire   [0:0] MultiPixStream2AXIvideo_U0_m_axis_video_TLAST;
wire   [0:0] MultiPixStream2AXIvideo_U0_m_axis_video_TID;
wire   [0:0] MultiPixStream2AXIvideo_U0_m_axis_video_TDEST;
wire   [0:0] cond_loc_channel_dout;
wire    cond_loc_channel_empty_n;
wire   [2:0] cond_loc_channel_num_data_valid;
wire   [2:0] cond_loc_channel_fifo_cap;
wire   [0:0] cond64_loc_channel_dout;
wire    cond64_loc_channel_empty_n;
wire   [2:0] cond64_loc_channel_num_data_valid;
wire   [2:0] cond64_loc_channel_fifo_cap;
wire    stream_in_full_n;
wire   [47:0] stream_in_dout;
wire    stream_in_empty_n;
wire   [4:0] stream_in_num_data_valid;
wire   [4:0] stream_in_fifo_cap;
wire    stream_in_hresampled_full_n;
wire   [47:0] stream_in_hresampled_dout;
wire    stream_in_hresampled_empty_n;
wire   [4:0] stream_in_hresampled_num_data_valid;
wire   [4:0] stream_in_hresampled_fifo_cap;
wire    stream_csc_full_n;
wire   [47:0] stream_csc_dout;
wire    stream_csc_empty_n;
wire   [4:0] stream_csc_num_data_valid;
wire   [4:0] stream_csc_fifo_cap;
wire    stream_out_hresampled_full_n;
wire   [47:0] stream_out_hresampled_dout;
wire    stream_out_hresampled_empty_n;
wire   [4:0] stream_out_hresampled_num_data_valid;
wire   [4:0] stream_out_hresampled_fifo_cap;
wire    ap_sync_ready;
reg    ap_sync_reg_Block_entry_proc_1_U0_ap_ready;
wire    ap_sync_Block_entry_proc_1_U0_ap_ready;
reg    ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready;
wire    ap_sync_AXIvideo2MultiPixStream_U0_ap_ready;
wire   [0:0] start_for_v_csc_core_U0_din;
wire    start_for_v_csc_core_U0_full_n;
wire   [0:0] start_for_v_csc_core_U0_dout;
wire    start_for_v_csc_core_U0_empty_n;
wire   [0:0] start_for_MultiPixStream2AXIvideo_U0_din;
wire    start_for_MultiPixStream2AXIvideo_U0_full_n;
wire   [0:0] start_for_MultiPixStream2AXIvideo_U0_dout;
wire    start_for_MultiPixStream2AXIvideo_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_cond64_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_cond_loc_channel = 1'b0;
#0 ap_sync_reg_Block_entry_proc_1_U0_ap_ready = 1'b0;
#0 ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready = 1'b0;
end

bd_d92b_csc_0_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .InVideoFormat(InVideoFormat),
    .OutVideoFormat(OutVideoFormat),
    .width(width),
    .height(height),
    .ColStart(ColStart),
    .ColEnd(ColEnd),
    .RowStart(RowStart),
    .RowEnd(RowEnd),
    .K11(K11),
    .K12(K12),
    .K13(K13),
    .K21(K21),
    .K22(K22),
    .K23(K23),
    .K31(K31),
    .K32(K32),
    .K33(K33),
    .ROffset(ROffset),
    .GOffset(GOffset),
    .BOffset(BOffset),
    .ClampMin(ClampMin),
    .ClipMax(ClipMax),
    .K11_2(K11_2),
    .K12_2(K12_2),
    .K13_2(K13_2),
    .K21_2(K21_2),
    .K22_2(K22_2),
    .K23_2(K23_2),
    .K31_2(K31_2),
    .K32_2(K32_2),
    .K33_2(K33_2),
    .ROffset_2(ROffset_2),
    .GOffset_2(GOffset_2),
    .BOffset_2(BOffset_2),
    .ClampMin_2(ClampMin_2),
    .ClipMax_2(ClipMax_2),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

bd_d92b_csc_0_Block_entry_proc_1 Block_entry_proc_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_entry_proc_1_U0_ap_start),
    .ap_done(Block_entry_proc_1_U0_ap_done),
    .ap_continue(Block_entry_proc_1_U0_ap_continue),
    .ap_idle(Block_entry_proc_1_U0_ap_idle),
    .ap_ready(Block_entry_proc_1_U0_ap_ready),
    .InVideoFormat(InVideoFormat),
    .OutVideoFormat(OutVideoFormat),
    .ap_return_0(Block_entry_proc_1_U0_ap_return_0),
    .ap_return_1(Block_entry_proc_1_U0_ap_return_1)
);

bd_d92b_csc_0_AXIvideo2MultiPixStream AXIvideo2MultiPixStream_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(AXIvideo2MultiPixStream_U0_ap_start),
    .ap_done(AXIvideo2MultiPixStream_U0_ap_done),
    .ap_continue(AXIvideo2MultiPixStream_U0_ap_continue),
    .ap_idle(AXIvideo2MultiPixStream_U0_ap_idle),
    .ap_ready(AXIvideo2MultiPixStream_U0_ap_ready),
    .height(height),
    .width(width),
    .InVideoFormat(InVideoFormat),
    .s_axis_video_TDATA(s_axis_video_TDATA),
    .s_axis_video_TVALID(s_axis_video_TVALID),
    .s_axis_video_TREADY(AXIvideo2MultiPixStream_U0_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP),
    .s_axis_video_TSTRB(s_axis_video_TSTRB),
    .s_axis_video_TUSER(s_axis_video_TUSER),
    .s_axis_video_TLAST(s_axis_video_TLAST),
    .s_axis_video_TID(s_axis_video_TID),
    .s_axis_video_TDEST(s_axis_video_TDEST),
    .stream_in_din(AXIvideo2MultiPixStream_U0_stream_in_din),
    .stream_in_full_n(stream_in_full_n),
    .stream_in_write(AXIvideo2MultiPixStream_U0_stream_in_write),
    .stream_in_num_data_valid(stream_in_num_data_valid),
    .stream_in_fifo_cap(stream_in_fifo_cap)
);

bd_d92b_csc_0_v_hcresampler_core v_hcresampler_core_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(v_hcresampler_core_U0_ap_start),
    .start_full_n(start_for_v_csc_core_U0_full_n),
    .ap_done(v_hcresampler_core_U0_ap_done),
    .ap_continue(v_hcresampler_core_U0_ap_continue),
    .ap_idle(v_hcresampler_core_U0_ap_idle),
    .ap_ready(v_hcresampler_core_U0_ap_ready),
    .start_out(v_hcresampler_core_U0_start_out),
    .start_write(v_hcresampler_core_U0_start_write),
    .height(height),
    .width(width),
    .p_read(cond_loc_channel_dout),
    .stream_in_dout(stream_in_dout),
    .stream_in_empty_n(stream_in_empty_n),
    .stream_in_read(v_hcresampler_core_U0_stream_in_read),
    .stream_in_num_data_valid(stream_in_num_data_valid),
    .stream_in_fifo_cap(stream_in_fifo_cap),
    .stream_in_hresampled_din(v_hcresampler_core_U0_stream_in_hresampled_din),
    .stream_in_hresampled_full_n(stream_in_hresampled_full_n),
    .stream_in_hresampled_write(v_hcresampler_core_U0_stream_in_hresampled_write),
    .stream_in_hresampled_num_data_valid(v_hcresampler_core_U0_stream_in_hresampled_num_data_valid),
    .stream_in_hresampled_fifo_cap(v_hcresampler_core_U0_stream_in_hresampled_fifo_cap)
);

bd_d92b_csc_0_v_csc_core v_csc_core_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(v_csc_core_U0_ap_start),
    .ap_done(v_csc_core_U0_ap_done),
    .ap_continue(v_csc_core_U0_ap_continue),
    .ap_idle(v_csc_core_U0_ap_idle),
    .ap_ready(v_csc_core_U0_ap_ready),
    .height(height),
    .width(width),
    .ColStart(ColStart),
    .ColEnd(ColEnd),
    .RowStart(RowStart),
    .RowEnd(RowEnd),
    .K11(K11),
    .K12(K12),
    .K13(K13),
    .K21(K21),
    .K22(K22),
    .K23(K23),
    .K31(K31),
    .K32(K32),
    .K33(K33),
    .ROffset(ROffset),
    .GOffset(GOffset),
    .BOffset(BOffset),
    .ClampMin(ClampMin),
    .ClipMax(ClipMax),
    .K11_2(K11_2),
    .K12_2(K12_2),
    .K13_2(K13_2),
    .K21_2(K21_2),
    .K22_2(K22_2),
    .K23_2(K23_2),
    .K31_2(K31_2),
    .K32_2(K32_2),
    .K33_2(K33_2),
    .ROffset_2(ROffset_2),
    .GOffset_2(GOffset_2),
    .BOffset_2(BOffset_2),
    .ClampMin_2(ClampMin_2),
    .ClipMax_2(ClipMax_2),
    .stream_in_hresampled_dout(stream_in_hresampled_dout),
    .stream_in_hresampled_empty_n(stream_in_hresampled_empty_n),
    .stream_in_hresampled_read(v_csc_core_U0_stream_in_hresampled_read),
    .stream_in_hresampled_num_data_valid(stream_in_hresampled_num_data_valid),
    .stream_in_hresampled_fifo_cap(stream_in_hresampled_fifo_cap),
    .stream_csc_din(v_csc_core_U0_stream_csc_din),
    .stream_csc_full_n(stream_csc_full_n),
    .stream_csc_write(v_csc_core_U0_stream_csc_write),
    .stream_csc_num_data_valid(v_csc_core_U0_stream_csc_num_data_valid),
    .stream_csc_fifo_cap(v_csc_core_U0_stream_csc_fifo_cap)
);

bd_d92b_csc_0_v_hcresampler_core_1 v_hcresampler_core_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(v_hcresampler_core_1_U0_ap_start),
    .start_full_n(start_for_MultiPixStream2AXIvideo_U0_full_n),
    .ap_done(v_hcresampler_core_1_U0_ap_done),
    .ap_continue(v_hcresampler_core_1_U0_ap_continue),
    .ap_idle(v_hcresampler_core_1_U0_ap_idle),
    .ap_ready(v_hcresampler_core_1_U0_ap_ready),
    .start_out(v_hcresampler_core_1_U0_start_out),
    .start_write(v_hcresampler_core_1_U0_start_write),
    .height(height),
    .width(width),
    .p_read(cond64_loc_channel_dout),
    .stream_csc_dout(stream_csc_dout),
    .stream_csc_empty_n(stream_csc_empty_n),
    .stream_csc_read(v_hcresampler_core_1_U0_stream_csc_read),
    .stream_csc_num_data_valid(stream_csc_num_data_valid),
    .stream_csc_fifo_cap(stream_csc_fifo_cap),
    .stream_out_hresampled_din(v_hcresampler_core_1_U0_stream_out_hresampled_din),
    .stream_out_hresampled_full_n(stream_out_hresampled_full_n),
    .stream_out_hresampled_write(v_hcresampler_core_1_U0_stream_out_hresampled_write),
    .stream_out_hresampled_num_data_valid(v_hcresampler_core_1_U0_stream_out_hresampled_num_data_valid),
    .stream_out_hresampled_fifo_cap(v_hcresampler_core_1_U0_stream_out_hresampled_fifo_cap)
);

bd_d92b_csc_0_MultiPixStream2AXIvideo MultiPixStream2AXIvideo_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(MultiPixStream2AXIvideo_U0_ap_start),
    .ap_done(MultiPixStream2AXIvideo_U0_ap_done),
    .ap_continue(MultiPixStream2AXIvideo_U0_ap_continue),
    .ap_idle(MultiPixStream2AXIvideo_U0_ap_idle),
    .ap_ready(MultiPixStream2AXIvideo_U0_ap_ready),
    .height(height),
    .width(width),
    .OutVideoFormat(OutVideoFormat),
    .stream_out_hresampled_dout(stream_out_hresampled_dout),
    .stream_out_hresampled_empty_n(stream_out_hresampled_empty_n),
    .stream_out_hresampled_read(MultiPixStream2AXIvideo_U0_stream_out_hresampled_read),
    .stream_out_hresampled_num_data_valid(stream_out_hresampled_num_data_valid),
    .stream_out_hresampled_fifo_cap(stream_out_hresampled_fifo_cap),
    .m_axis_video_TDATA(MultiPixStream2AXIvideo_U0_m_axis_video_TDATA),
    .m_axis_video_TVALID(MultiPixStream2AXIvideo_U0_m_axis_video_TVALID),
    .m_axis_video_TREADY(m_axis_video_TREADY),
    .m_axis_video_TKEEP(MultiPixStream2AXIvideo_U0_m_axis_video_TKEEP),
    .m_axis_video_TSTRB(MultiPixStream2AXIvideo_U0_m_axis_video_TSTRB),
    .m_axis_video_TUSER(MultiPixStream2AXIvideo_U0_m_axis_video_TUSER),
    .m_axis_video_TLAST(MultiPixStream2AXIvideo_U0_m_axis_video_TLAST),
    .m_axis_video_TID(MultiPixStream2AXIvideo_U0_m_axis_video_TID),
    .m_axis_video_TDEST(MultiPixStream2AXIvideo_U0_m_axis_video_TDEST)
);

bd_d92b_csc_0_fifo_w1_d2_S cond_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_proc_1_U0_ap_return_0),
    .if_full_n(cond_loc_channel_full_n),
    .if_write(ap_channel_done_cond_loc_channel),
    .if_dout(cond_loc_channel_dout),
    .if_empty_n(cond_loc_channel_empty_n),
    .if_read(v_hcresampler_core_U0_ap_ready),
    .if_num_data_valid(cond_loc_channel_num_data_valid),
    .if_fifo_cap(cond_loc_channel_fifo_cap)
);

bd_d92b_csc_0_fifo_w1_d4_S cond64_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_proc_1_U0_ap_return_1),
    .if_full_n(cond64_loc_channel_full_n),
    .if_write(ap_channel_done_cond64_loc_channel),
    .if_dout(cond64_loc_channel_dout),
    .if_empty_n(cond64_loc_channel_empty_n),
    .if_read(v_hcresampler_core_1_U0_ap_ready),
    .if_num_data_valid(cond64_loc_channel_num_data_valid),
    .if_fifo_cap(cond64_loc_channel_fifo_cap)
);

bd_d92b_csc_0_fifo_w48_d16_S stream_in_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2MultiPixStream_U0_stream_in_din),
    .if_full_n(stream_in_full_n),
    .if_write(AXIvideo2MultiPixStream_U0_stream_in_write),
    .if_dout(stream_in_dout),
    .if_empty_n(stream_in_empty_n),
    .if_read(v_hcresampler_core_U0_stream_in_read),
    .if_num_data_valid(stream_in_num_data_valid),
    .if_fifo_cap(stream_in_fifo_cap)
);

bd_d92b_csc_0_fifo_w48_d16_S stream_in_hresampled_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_hcresampler_core_U0_stream_in_hresampled_din),
    .if_full_n(stream_in_hresampled_full_n),
    .if_write(v_hcresampler_core_U0_stream_in_hresampled_write),
    .if_dout(stream_in_hresampled_dout),
    .if_empty_n(stream_in_hresampled_empty_n),
    .if_read(v_csc_core_U0_stream_in_hresampled_read),
    .if_num_data_valid(stream_in_hresampled_num_data_valid),
    .if_fifo_cap(stream_in_hresampled_fifo_cap)
);

bd_d92b_csc_0_fifo_w48_d16_S stream_csc_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_csc_core_U0_stream_csc_din),
    .if_full_n(stream_csc_full_n),
    .if_write(v_csc_core_U0_stream_csc_write),
    .if_dout(stream_csc_dout),
    .if_empty_n(stream_csc_empty_n),
    .if_read(v_hcresampler_core_1_U0_stream_csc_read),
    .if_num_data_valid(stream_csc_num_data_valid),
    .if_fifo_cap(stream_csc_fifo_cap)
);

bd_d92b_csc_0_fifo_w48_d16_S stream_out_hresampled_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_hcresampler_core_1_U0_stream_out_hresampled_din),
    .if_full_n(stream_out_hresampled_full_n),
    .if_write(v_hcresampler_core_1_U0_stream_out_hresampled_write),
    .if_dout(stream_out_hresampled_dout),
    .if_empty_n(stream_out_hresampled_empty_n),
    .if_read(MultiPixStream2AXIvideo_U0_stream_out_hresampled_read),
    .if_num_data_valid(stream_out_hresampled_num_data_valid),
    .if_fifo_cap(stream_out_hresampled_fifo_cap)
);

bd_d92b_csc_0_start_for_v_csc_core_U0 start_for_v_csc_core_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_v_csc_core_U0_din),
    .if_full_n(start_for_v_csc_core_U0_full_n),
    .if_write(v_hcresampler_core_U0_start_write),
    .if_dout(start_for_v_csc_core_U0_dout),
    .if_empty_n(start_for_v_csc_core_U0_empty_n),
    .if_read(v_csc_core_U0_ap_ready)
);

bd_d92b_csc_0_start_for_MultiPixStream2AXIvideo_U0 start_for_MultiPixStream2AXIvideo_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_MultiPixStream2AXIvideo_U0_din),
    .if_full_n(start_for_MultiPixStream2AXIvideo_U0_full_n),
    .if_write(v_hcresampler_core_1_U0_start_write),
    .if_dout(start_for_MultiPixStream2AXIvideo_U0_dout),
    .if_empty_n(start_for_MultiPixStream2AXIvideo_U0_empty_n),
    .if_read(MultiPixStream2AXIvideo_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready <= ap_sync_AXIvideo2MultiPixStream_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Block_entry_proc_1_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Block_entry_proc_1_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Block_entry_proc_1_U0_ap_ready <= ap_sync_Block_entry_proc_1_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_cond64_loc_channel <= 1'b0;
    end else begin
        if (((Block_entry_proc_1_U0_ap_done & Block_entry_proc_1_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_cond64_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_cond64_loc_channel <= ap_sync_channel_write_cond64_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_cond_loc_channel <= 1'b0;
    end else begin
        if (((Block_entry_proc_1_U0_ap_done & Block_entry_proc_1_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_cond_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_cond_loc_channel <= ap_sync_channel_write_cond_loc_channel;
        end
    end
end

assign AXIvideo2MultiPixStream_U0_ap_continue = 1'b1;

assign AXIvideo2MultiPixStream_U0_ap_start = ((ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready ^ 1'b1) & ap_start & 1'b1);

assign Block_entry_proc_1_U0_ap_continue = (ap_sync_channel_write_cond_loc_channel & ap_sync_channel_write_cond64_loc_channel);

assign Block_entry_proc_1_U0_ap_start = ((ap_sync_reg_Block_entry_proc_1_U0_ap_ready ^ 1'b1) & ap_start & 1'b1);

assign MultiPixStream2AXIvideo_U0_ap_continue = 1'b1;

assign MultiPixStream2AXIvideo_U0_ap_start = start_for_MultiPixStream2AXIvideo_U0_empty_n;

assign ap_channel_done_cond64_loc_channel = ((ap_sync_reg_channel_write_cond64_loc_channel ^ 1'b1) & Block_entry_proc_1_U0_ap_done);

assign ap_channel_done_cond_loc_channel = ((ap_sync_reg_channel_write_cond_loc_channel ^ 1'b1) & Block_entry_proc_1_U0_ap_done);

assign ap_done = MultiPixStream2AXIvideo_U0_ap_done;

assign ap_idle = (v_hcresampler_core_U0_ap_idle & v_hcresampler_core_1_U0_ap_idle & v_csc_core_U0_ap_idle & (cond64_loc_channel_empty_n ^ 1'b1) & (cond_loc_channel_empty_n ^ 1'b1) & MultiPixStream2AXIvideo_U0_ap_idle & Block_entry_proc_1_U0_ap_idle & AXIvideo2MultiPixStream_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_AXIvideo2MultiPixStream_U0_ap_ready = (ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready | AXIvideo2MultiPixStream_U0_ap_ready);

assign ap_sync_Block_entry_proc_1_U0_ap_ready = (ap_sync_reg_Block_entry_proc_1_U0_ap_ready | Block_entry_proc_1_U0_ap_ready);

assign ap_sync_channel_write_cond64_loc_channel = ((cond64_loc_channel_full_n & ap_channel_done_cond64_loc_channel) | ap_sync_reg_channel_write_cond64_loc_channel);

assign ap_sync_channel_write_cond_loc_channel = ((cond_loc_channel_full_n & ap_channel_done_cond_loc_channel) | ap_sync_reg_channel_write_cond_loc_channel);

assign ap_sync_ready = (ap_sync_Block_entry_proc_1_U0_ap_ready & ap_sync_AXIvideo2MultiPixStream_U0_ap_ready);

assign m_axis_video_TDATA = MultiPixStream2AXIvideo_U0_m_axis_video_TDATA;

assign m_axis_video_TDEST = MultiPixStream2AXIvideo_U0_m_axis_video_TDEST;

assign m_axis_video_TID = MultiPixStream2AXIvideo_U0_m_axis_video_TID;

assign m_axis_video_TKEEP = MultiPixStream2AXIvideo_U0_m_axis_video_TKEEP;

assign m_axis_video_TLAST = MultiPixStream2AXIvideo_U0_m_axis_video_TLAST;

assign m_axis_video_TSTRB = MultiPixStream2AXIvideo_U0_m_axis_video_TSTRB;

assign m_axis_video_TUSER = MultiPixStream2AXIvideo_U0_m_axis_video_TUSER;

assign m_axis_video_TVALID = MultiPixStream2AXIvideo_U0_m_axis_video_TVALID;

assign s_axis_video_TREADY = AXIvideo2MultiPixStream_U0_s_axis_video_TREADY;

assign start_for_MultiPixStream2AXIvideo_U0_din = 1'b1;

assign start_for_v_csc_core_U0_din = 1'b1;

assign v_csc_core_U0_ap_continue = 1'b1;

assign v_csc_core_U0_ap_start = start_for_v_csc_core_U0_empty_n;

assign v_csc_core_U0_stream_csc_fifo_cap = stream_csc_fifo_cap;

assign v_csc_core_U0_stream_csc_num_data_valid = stream_csc_num_data_valid;

assign v_hcresampler_core_1_U0_ap_continue = 1'b1;

assign v_hcresampler_core_1_U0_ap_start = cond64_loc_channel_empty_n;

assign v_hcresampler_core_1_U0_stream_out_hresampled_fifo_cap = stream_out_hresampled_fifo_cap;

assign v_hcresampler_core_1_U0_stream_out_hresampled_num_data_valid = stream_out_hresampled_num_data_valid;

assign v_hcresampler_core_U0_ap_continue = 1'b1;

assign v_hcresampler_core_U0_ap_start = cond_loc_channel_empty_n;

assign v_hcresampler_core_U0_stream_in_hresampled_fifo_cap = stream_in_hresampled_fifo_cap;

assign v_hcresampler_core_U0_stream_in_hresampled_num_data_valid = stream_in_hresampled_num_data_valid;

endmodule //bd_d92b_csc_0_v_csc
