-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bd_197a_csc_0_v_csc is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 9;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32 );
port (
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    interrupt : OUT STD_LOGIC;
    s_axis_video_TDATA : IN STD_LOGIC_VECTOR (47 downto 0);
    s_axis_video_TKEEP : IN STD_LOGIC_VECTOR (5 downto 0);
    s_axis_video_TSTRB : IN STD_LOGIC_VECTOR (5 downto 0);
    s_axis_video_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TDATA : OUT STD_LOGIC_VECTOR (47 downto 0);
    m_axis_video_TKEEP : OUT STD_LOGIC_VECTOR (5 downto 0);
    m_axis_video_TSTRB : OUT STD_LOGIC_VECTOR (5 downto 0);
    m_axis_video_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TVALID : IN STD_LOGIC;
    s_axis_video_TREADY : OUT STD_LOGIC;
    m_axis_video_TVALID : OUT STD_LOGIC;
    m_axis_video_TREADY : IN STD_LOGIC );
end;


architecture behav of bd_197a_csc_0_v_csc is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "bd_197a_csc_0_v_csc,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu2cg-sfvc784-1-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=3.442875,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=4306,HLS_SYN_LUT=6102,HLS_VERSION=2025_2}";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal InVideoFormat : STD_LOGIC_VECTOR (7 downto 0);
    signal OutVideoFormat : STD_LOGIC_VECTOR (7 downto 0);
    signal width : STD_LOGIC_VECTOR (15 downto 0);
    signal height : STD_LOGIC_VECTOR (15 downto 0);
    signal ColStart : STD_LOGIC_VECTOR (15 downto 0);
    signal ColEnd : STD_LOGIC_VECTOR (15 downto 0);
    signal RowStart : STD_LOGIC_VECTOR (15 downto 0);
    signal RowEnd : STD_LOGIC_VECTOR (15 downto 0);
    signal K11 : STD_LOGIC_VECTOR (15 downto 0);
    signal K12 : STD_LOGIC_VECTOR (15 downto 0);
    signal K13 : STD_LOGIC_VECTOR (15 downto 0);
    signal K21 : STD_LOGIC_VECTOR (15 downto 0);
    signal K22 : STD_LOGIC_VECTOR (15 downto 0);
    signal K23 : STD_LOGIC_VECTOR (15 downto 0);
    signal K31 : STD_LOGIC_VECTOR (15 downto 0);
    signal K32 : STD_LOGIC_VECTOR (15 downto 0);
    signal K33 : STD_LOGIC_VECTOR (15 downto 0);
    signal ROffset : STD_LOGIC_VECTOR (9 downto 0);
    signal GOffset : STD_LOGIC_VECTOR (9 downto 0);
    signal BOffset : STD_LOGIC_VECTOR (9 downto 0);
    signal ClampMin : STD_LOGIC_VECTOR (7 downto 0);
    signal ClipMax : STD_LOGIC_VECTOR (7 downto 0);
    signal K11_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal K12_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal K13_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal K21_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal K22_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal K23_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal K31_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal K32_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal K33_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ROffset_2 : STD_LOGIC_VECTOR (9 downto 0);
    signal GOffset_2 : STD_LOGIC_VECTOR (9 downto 0);
    signal BOffset_2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ClampMin_2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ClipMax_2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_start : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal Block_entry_proc_1_U0_ap_start : STD_LOGIC;
    signal Block_entry_proc_1_U0_ap_done : STD_LOGIC;
    signal Block_entry_proc_1_U0_ap_continue : STD_LOGIC;
    signal Block_entry_proc_1_U0_ap_idle : STD_LOGIC;
    signal Block_entry_proc_1_U0_ap_ready : STD_LOGIC;
    signal Block_entry_proc_1_U0_ap_return_0 : STD_LOGIC_VECTOR (0 downto 0);
    signal Block_entry_proc_1_U0_ap_return_1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_channel_done_cond64_loc_channel : STD_LOGIC;
    signal cond64_loc_channel_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_cond64_loc_channel : STD_LOGIC := '0';
    signal ap_sync_channel_write_cond64_loc_channel : STD_LOGIC;
    signal ap_channel_done_cond_loc_channel : STD_LOGIC;
    signal cond_loc_channel_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_cond_loc_channel : STD_LOGIC := '0';
    signal ap_sync_channel_write_cond_loc_channel : STD_LOGIC;
    signal AXIvideo2MultiPixStream_U0_ap_start : STD_LOGIC;
    signal AXIvideo2MultiPixStream_U0_ap_done : STD_LOGIC;
    signal AXIvideo2MultiPixStream_U0_ap_continue : STD_LOGIC;
    signal AXIvideo2MultiPixStream_U0_ap_idle : STD_LOGIC;
    signal AXIvideo2MultiPixStream_U0_ap_ready : STD_LOGIC;
    signal AXIvideo2MultiPixStream_U0_s_axis_video_TREADY : STD_LOGIC;
    signal AXIvideo2MultiPixStream_U0_stream_in_din : STD_LOGIC_VECTOR (47 downto 0);
    signal AXIvideo2MultiPixStream_U0_stream_in_write : STD_LOGIC;
    signal v_hcresampler_core_U0_ap_start : STD_LOGIC;
    signal v_hcresampler_core_U0_ap_done : STD_LOGIC;
    signal v_hcresampler_core_U0_ap_continue : STD_LOGIC;
    signal v_hcresampler_core_U0_ap_idle : STD_LOGIC;
    signal v_hcresampler_core_U0_ap_ready : STD_LOGIC;
    signal v_hcresampler_core_U0_start_out : STD_LOGIC;
    signal v_hcresampler_core_U0_start_write : STD_LOGIC;
    signal v_hcresampler_core_U0_stream_in_read : STD_LOGIC;
    signal v_hcresampler_core_U0_stream_in_hresampled_din : STD_LOGIC_VECTOR (47 downto 0);
    signal v_hcresampler_core_U0_stream_in_hresampled_write : STD_LOGIC;
    signal v_hcresampler_core_U0_stream_in_hresampled_num_data_valid : STD_LOGIC_VECTOR (31 downto 0);
    signal v_hcresampler_core_U0_stream_in_hresampled_fifo_cap : STD_LOGIC_VECTOR (31 downto 0);
    signal v_csc_core_U0_ap_start : STD_LOGIC;
    signal v_csc_core_U0_ap_done : STD_LOGIC;
    signal v_csc_core_U0_ap_continue : STD_LOGIC;
    signal v_csc_core_U0_ap_idle : STD_LOGIC;
    signal v_csc_core_U0_ap_ready : STD_LOGIC;
    signal v_csc_core_U0_stream_in_hresampled_read : STD_LOGIC;
    signal v_csc_core_U0_stream_csc_din : STD_LOGIC_VECTOR (47 downto 0);
    signal v_csc_core_U0_stream_csc_write : STD_LOGIC;
    signal v_csc_core_U0_stream_csc_num_data_valid : STD_LOGIC_VECTOR (31 downto 0);
    signal v_csc_core_U0_stream_csc_fifo_cap : STD_LOGIC_VECTOR (31 downto 0);
    signal v_hcresampler_core_1_U0_ap_start : STD_LOGIC;
    signal v_hcresampler_core_1_U0_ap_done : STD_LOGIC;
    signal v_hcresampler_core_1_U0_ap_continue : STD_LOGIC;
    signal v_hcresampler_core_1_U0_ap_idle : STD_LOGIC;
    signal v_hcresampler_core_1_U0_ap_ready : STD_LOGIC;
    signal v_hcresampler_core_1_U0_start_out : STD_LOGIC;
    signal v_hcresampler_core_1_U0_start_write : STD_LOGIC;
    signal v_hcresampler_core_1_U0_stream_csc_read : STD_LOGIC;
    signal v_hcresampler_core_1_U0_stream_out_hresampled_din : STD_LOGIC_VECTOR (47 downto 0);
    signal v_hcresampler_core_1_U0_stream_out_hresampled_write : STD_LOGIC;
    signal v_hcresampler_core_1_U0_stream_out_hresampled_num_data_valid : STD_LOGIC_VECTOR (31 downto 0);
    signal v_hcresampler_core_1_U0_stream_out_hresampled_fifo_cap : STD_LOGIC_VECTOR (31 downto 0);
    signal MultiPixStream2AXIvideo_U0_ap_start : STD_LOGIC;
    signal MultiPixStream2AXIvideo_U0_ap_done : STD_LOGIC;
    signal MultiPixStream2AXIvideo_U0_ap_continue : STD_LOGIC;
    signal MultiPixStream2AXIvideo_U0_ap_idle : STD_LOGIC;
    signal MultiPixStream2AXIvideo_U0_ap_ready : STD_LOGIC;
    signal MultiPixStream2AXIvideo_U0_stream_out_hresampled_read : STD_LOGIC;
    signal MultiPixStream2AXIvideo_U0_m_axis_video_TDATA : STD_LOGIC_VECTOR (47 downto 0);
    signal MultiPixStream2AXIvideo_U0_m_axis_video_TVALID : STD_LOGIC;
    signal MultiPixStream2AXIvideo_U0_m_axis_video_TKEEP : STD_LOGIC_VECTOR (5 downto 0);
    signal MultiPixStream2AXIvideo_U0_m_axis_video_TSTRB : STD_LOGIC_VECTOR (5 downto 0);
    signal MultiPixStream2AXIvideo_U0_m_axis_video_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal MultiPixStream2AXIvideo_U0_m_axis_video_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal MultiPixStream2AXIvideo_U0_m_axis_video_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal MultiPixStream2AXIvideo_U0_m_axis_video_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal cond_loc_channel_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal cond_loc_channel_empty_n : STD_LOGIC;
    signal cond_loc_channel_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal cond_loc_channel_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal cond64_loc_channel_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal cond64_loc_channel_empty_n : STD_LOGIC;
    signal cond64_loc_channel_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal cond64_loc_channel_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal stream_in_full_n : STD_LOGIC;
    signal stream_in_dout : STD_LOGIC_VECTOR (47 downto 0);
    signal stream_in_empty_n : STD_LOGIC;
    signal stream_in_num_data_valid : STD_LOGIC_VECTOR (4 downto 0);
    signal stream_in_fifo_cap : STD_LOGIC_VECTOR (4 downto 0);
    signal stream_in_hresampled_full_n : STD_LOGIC;
    signal stream_in_hresampled_dout : STD_LOGIC_VECTOR (47 downto 0);
    signal stream_in_hresampled_empty_n : STD_LOGIC;
    signal stream_in_hresampled_num_data_valid : STD_LOGIC_VECTOR (4 downto 0);
    signal stream_in_hresampled_fifo_cap : STD_LOGIC_VECTOR (4 downto 0);
    signal stream_csc_full_n : STD_LOGIC;
    signal stream_csc_dout : STD_LOGIC_VECTOR (47 downto 0);
    signal stream_csc_empty_n : STD_LOGIC;
    signal stream_csc_num_data_valid : STD_LOGIC_VECTOR (4 downto 0);
    signal stream_csc_fifo_cap : STD_LOGIC_VECTOR (4 downto 0);
    signal stream_out_hresampled_full_n : STD_LOGIC;
    signal stream_out_hresampled_dout : STD_LOGIC_VECTOR (47 downto 0);
    signal stream_out_hresampled_empty_n : STD_LOGIC;
    signal stream_out_hresampled_num_data_valid : STD_LOGIC_VECTOR (4 downto 0);
    signal stream_out_hresampled_fifo_cap : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_Block_entry_proc_1_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_Block_entry_proc_1_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_AXIvideo2MultiPixStream_U0_ap_ready : STD_LOGIC;
    signal start_for_v_csc_core_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_v_csc_core_U0_full_n : STD_LOGIC;
    signal start_for_v_csc_core_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_v_csc_core_U0_empty_n : STD_LOGIC;
    signal start_for_MultiPixStream2AXIvideo_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_MultiPixStream2AXIvideo_U0_full_n : STD_LOGIC;
    signal start_for_MultiPixStream2AXIvideo_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_MultiPixStream2AXIvideo_U0_empty_n : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component bd_197a_csc_0_Block_entry_proc_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        InVideoFormat : IN STD_LOGIC_VECTOR (7 downto 0);
        OutVideoFormat : IN STD_LOGIC_VECTOR (7 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component bd_197a_csc_0_AXIvideo2MultiPixStream IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        height : IN STD_LOGIC_VECTOR (15 downto 0);
        width : IN STD_LOGIC_VECTOR (15 downto 0);
        InVideoFormat : IN STD_LOGIC_VECTOR (7 downto 0);
        s_axis_video_TDATA : IN STD_LOGIC_VECTOR (47 downto 0);
        s_axis_video_TVALID : IN STD_LOGIC;
        s_axis_video_TREADY : OUT STD_LOGIC;
        s_axis_video_TKEEP : IN STD_LOGIC_VECTOR (5 downto 0);
        s_axis_video_TSTRB : IN STD_LOGIC_VECTOR (5 downto 0);
        s_axis_video_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        stream_in_din : OUT STD_LOGIC_VECTOR (47 downto 0);
        stream_in_full_n : IN STD_LOGIC;
        stream_in_write : OUT STD_LOGIC;
        stream_in_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_in_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component bd_197a_csc_0_v_hcresampler_core IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        height : IN STD_LOGIC_VECTOR (15 downto 0);
        width : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read : IN STD_LOGIC_VECTOR (0 downto 0);
        stream_in_dout : IN STD_LOGIC_VECTOR (47 downto 0);
        stream_in_empty_n : IN STD_LOGIC;
        stream_in_read : OUT STD_LOGIC;
        stream_in_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_in_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_in_hresampled_din : OUT STD_LOGIC_VECTOR (47 downto 0);
        stream_in_hresampled_full_n : IN STD_LOGIC;
        stream_in_hresampled_write : OUT STD_LOGIC;
        stream_in_hresampled_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        stream_in_hresampled_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component bd_197a_csc_0_v_csc_core IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        height : IN STD_LOGIC_VECTOR (15 downto 0);
        width : IN STD_LOGIC_VECTOR (15 downto 0);
        ColStart : IN STD_LOGIC_VECTOR (15 downto 0);
        ColEnd : IN STD_LOGIC_VECTOR (15 downto 0);
        RowStart : IN STD_LOGIC_VECTOR (15 downto 0);
        RowEnd : IN STD_LOGIC_VECTOR (15 downto 0);
        K11 : IN STD_LOGIC_VECTOR (15 downto 0);
        K12 : IN STD_LOGIC_VECTOR (15 downto 0);
        K13 : IN STD_LOGIC_VECTOR (15 downto 0);
        K21 : IN STD_LOGIC_VECTOR (15 downto 0);
        K22 : IN STD_LOGIC_VECTOR (15 downto 0);
        K23 : IN STD_LOGIC_VECTOR (15 downto 0);
        K31 : IN STD_LOGIC_VECTOR (15 downto 0);
        K32 : IN STD_LOGIC_VECTOR (15 downto 0);
        K33 : IN STD_LOGIC_VECTOR (15 downto 0);
        ROffset : IN STD_LOGIC_VECTOR (9 downto 0);
        GOffset : IN STD_LOGIC_VECTOR (9 downto 0);
        BOffset : IN STD_LOGIC_VECTOR (9 downto 0);
        ClampMin : IN STD_LOGIC_VECTOR (7 downto 0);
        ClipMax : IN STD_LOGIC_VECTOR (7 downto 0);
        K11_2 : IN STD_LOGIC_VECTOR (15 downto 0);
        K12_2 : IN STD_LOGIC_VECTOR (15 downto 0);
        K13_2 : IN STD_LOGIC_VECTOR (15 downto 0);
        K21_2 : IN STD_LOGIC_VECTOR (15 downto 0);
        K22_2 : IN STD_LOGIC_VECTOR (15 downto 0);
        K23_2 : IN STD_LOGIC_VECTOR (15 downto 0);
        K31_2 : IN STD_LOGIC_VECTOR (15 downto 0);
        K32_2 : IN STD_LOGIC_VECTOR (15 downto 0);
        K33_2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ROffset_2 : IN STD_LOGIC_VECTOR (9 downto 0);
        GOffset_2 : IN STD_LOGIC_VECTOR (9 downto 0);
        BOffset_2 : IN STD_LOGIC_VECTOR (9 downto 0);
        ClampMin_2 : IN STD_LOGIC_VECTOR (7 downto 0);
        ClipMax_2 : IN STD_LOGIC_VECTOR (7 downto 0);
        stream_in_hresampled_dout : IN STD_LOGIC_VECTOR (47 downto 0);
        stream_in_hresampled_empty_n : IN STD_LOGIC;
        stream_in_hresampled_read : OUT STD_LOGIC;
        stream_in_hresampled_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_in_hresampled_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_csc_din : OUT STD_LOGIC_VECTOR (47 downto 0);
        stream_csc_full_n : IN STD_LOGIC;
        stream_csc_write : OUT STD_LOGIC;
        stream_csc_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        stream_csc_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component bd_197a_csc_0_v_hcresampler_core_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        height : IN STD_LOGIC_VECTOR (15 downto 0);
        width : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read : IN STD_LOGIC_VECTOR (0 downto 0);
        stream_csc_dout : IN STD_LOGIC_VECTOR (47 downto 0);
        stream_csc_empty_n : IN STD_LOGIC;
        stream_csc_read : OUT STD_LOGIC;
        stream_csc_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_csc_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_out_hresampled_din : OUT STD_LOGIC_VECTOR (47 downto 0);
        stream_out_hresampled_full_n : IN STD_LOGIC;
        stream_out_hresampled_write : OUT STD_LOGIC;
        stream_out_hresampled_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        stream_out_hresampled_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component bd_197a_csc_0_MultiPixStream2AXIvideo IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        height : IN STD_LOGIC_VECTOR (15 downto 0);
        width : IN STD_LOGIC_VECTOR (15 downto 0);
        OutVideoFormat : IN STD_LOGIC_VECTOR (7 downto 0);
        stream_out_hresampled_dout : IN STD_LOGIC_VECTOR (47 downto 0);
        stream_out_hresampled_empty_n : IN STD_LOGIC;
        stream_out_hresampled_read : OUT STD_LOGIC;
        stream_out_hresampled_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_out_hresampled_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        m_axis_video_TDATA : OUT STD_LOGIC_VECTOR (47 downto 0);
        m_axis_video_TVALID : OUT STD_LOGIC;
        m_axis_video_TREADY : IN STD_LOGIC;
        m_axis_video_TKEEP : OUT STD_LOGIC_VECTOR (5 downto 0);
        m_axis_video_TSTRB : OUT STD_LOGIC_VECTOR (5 downto 0);
        m_axis_video_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axis_video_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axis_video_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axis_video_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component bd_197a_csc_0_fifo_w1_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component bd_197a_csc_0_fifo_w1_d4_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component bd_197a_csc_0_fifo_w48_d16_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (47 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (47 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (4 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component bd_197a_csc_0_start_for_v_csc_core_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component bd_197a_csc_0_start_for_MultiPixStream2AXIvideo_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component bd_197a_csc_0_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        InVideoFormat : OUT STD_LOGIC_VECTOR (7 downto 0);
        OutVideoFormat : OUT STD_LOGIC_VECTOR (7 downto 0);
        width : OUT STD_LOGIC_VECTOR (15 downto 0);
        height : OUT STD_LOGIC_VECTOR (15 downto 0);
        ColStart : OUT STD_LOGIC_VECTOR (15 downto 0);
        ColEnd : OUT STD_LOGIC_VECTOR (15 downto 0);
        RowStart : OUT STD_LOGIC_VECTOR (15 downto 0);
        RowEnd : OUT STD_LOGIC_VECTOR (15 downto 0);
        K11 : OUT STD_LOGIC_VECTOR (15 downto 0);
        K12 : OUT STD_LOGIC_VECTOR (15 downto 0);
        K13 : OUT STD_LOGIC_VECTOR (15 downto 0);
        K21 : OUT STD_LOGIC_VECTOR (15 downto 0);
        K22 : OUT STD_LOGIC_VECTOR (15 downto 0);
        K23 : OUT STD_LOGIC_VECTOR (15 downto 0);
        K31 : OUT STD_LOGIC_VECTOR (15 downto 0);
        K32 : OUT STD_LOGIC_VECTOR (15 downto 0);
        K33 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ROffset : OUT STD_LOGIC_VECTOR (9 downto 0);
        GOffset : OUT STD_LOGIC_VECTOR (9 downto 0);
        BOffset : OUT STD_LOGIC_VECTOR (9 downto 0);
        ClampMin : OUT STD_LOGIC_VECTOR (7 downto 0);
        ClipMax : OUT STD_LOGIC_VECTOR (7 downto 0);
        K11_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        K12_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        K13_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        K21_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        K22_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        K23_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        K31_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        K32_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        K33_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ROffset_2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        GOffset_2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        BOffset_2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ClampMin_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ClipMax_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;



begin
    CTRL_s_axi_U : component bd_197a_csc_0_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        InVideoFormat => InVideoFormat,
        OutVideoFormat => OutVideoFormat,
        width => width,
        height => height,
        ColStart => ColStart,
        ColEnd => ColEnd,
        RowStart => RowStart,
        RowEnd => RowEnd,
        K11 => K11,
        K12 => K12,
        K13 => K13,
        K21 => K21,
        K22 => K22,
        K23 => K23,
        K31 => K31,
        K32 => K32,
        K33 => K33,
        ROffset => ROffset,
        GOffset => GOffset,
        BOffset => BOffset,
        ClampMin => ClampMin,
        ClipMax => ClipMax,
        K11_2 => K11_2,
        K12_2 => K12_2,
        K13_2 => K13_2,
        K21_2 => K21_2,
        K22_2 => K22_2,
        K23_2 => K23_2,
        K31_2 => K31_2,
        K32_2 => K32_2,
        K33_2 => K33_2,
        ROffset_2 => ROffset_2,
        GOffset_2 => GOffset_2,
        BOffset_2 => BOffset_2,
        ClampMin_2 => ClampMin_2,
        ClipMax_2 => ClipMax_2,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    Block_entry_proc_1_U0 : component bd_197a_csc_0_Block_entry_proc_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Block_entry_proc_1_U0_ap_start,
        ap_done => Block_entry_proc_1_U0_ap_done,
        ap_continue => Block_entry_proc_1_U0_ap_continue,
        ap_idle => Block_entry_proc_1_U0_ap_idle,
        ap_ready => Block_entry_proc_1_U0_ap_ready,
        InVideoFormat => InVideoFormat,
        OutVideoFormat => OutVideoFormat,
        ap_return_0 => Block_entry_proc_1_U0_ap_return_0,
        ap_return_1 => Block_entry_proc_1_U0_ap_return_1);

    AXIvideo2MultiPixStream_U0 : component bd_197a_csc_0_AXIvideo2MultiPixStream
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => AXIvideo2MultiPixStream_U0_ap_start,
        ap_done => AXIvideo2MultiPixStream_U0_ap_done,
        ap_continue => AXIvideo2MultiPixStream_U0_ap_continue,
        ap_idle => AXIvideo2MultiPixStream_U0_ap_idle,
        ap_ready => AXIvideo2MultiPixStream_U0_ap_ready,
        height => height,
        width => width,
        InVideoFormat => InVideoFormat,
        s_axis_video_TDATA => s_axis_video_TDATA,
        s_axis_video_TVALID => s_axis_video_TVALID,
        s_axis_video_TREADY => AXIvideo2MultiPixStream_U0_s_axis_video_TREADY,
        s_axis_video_TKEEP => s_axis_video_TKEEP,
        s_axis_video_TSTRB => s_axis_video_TSTRB,
        s_axis_video_TUSER => s_axis_video_TUSER,
        s_axis_video_TLAST => s_axis_video_TLAST,
        s_axis_video_TID => s_axis_video_TID,
        s_axis_video_TDEST => s_axis_video_TDEST,
        stream_in_din => AXIvideo2MultiPixStream_U0_stream_in_din,
        stream_in_full_n => stream_in_full_n,
        stream_in_write => AXIvideo2MultiPixStream_U0_stream_in_write,
        stream_in_num_data_valid => stream_in_num_data_valid,
        stream_in_fifo_cap => stream_in_fifo_cap);

    v_hcresampler_core_U0 : component bd_197a_csc_0_v_hcresampler_core
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => v_hcresampler_core_U0_ap_start,
        start_full_n => start_for_v_csc_core_U0_full_n,
        ap_done => v_hcresampler_core_U0_ap_done,
        ap_continue => v_hcresampler_core_U0_ap_continue,
        ap_idle => v_hcresampler_core_U0_ap_idle,
        ap_ready => v_hcresampler_core_U0_ap_ready,
        start_out => v_hcresampler_core_U0_start_out,
        start_write => v_hcresampler_core_U0_start_write,
        height => height,
        width => width,
        p_read => cond_loc_channel_dout,
        stream_in_dout => stream_in_dout,
        stream_in_empty_n => stream_in_empty_n,
        stream_in_read => v_hcresampler_core_U0_stream_in_read,
        stream_in_num_data_valid => stream_in_num_data_valid,
        stream_in_fifo_cap => stream_in_fifo_cap,
        stream_in_hresampled_din => v_hcresampler_core_U0_stream_in_hresampled_din,
        stream_in_hresampled_full_n => stream_in_hresampled_full_n,
        stream_in_hresampled_write => v_hcresampler_core_U0_stream_in_hresampled_write,
        stream_in_hresampled_num_data_valid => v_hcresampler_core_U0_stream_in_hresampled_num_data_valid,
        stream_in_hresampled_fifo_cap => v_hcresampler_core_U0_stream_in_hresampled_fifo_cap);

    v_csc_core_U0 : component bd_197a_csc_0_v_csc_core
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => v_csc_core_U0_ap_start,
        ap_done => v_csc_core_U0_ap_done,
        ap_continue => v_csc_core_U0_ap_continue,
        ap_idle => v_csc_core_U0_ap_idle,
        ap_ready => v_csc_core_U0_ap_ready,
        height => height,
        width => width,
        ColStart => ColStart,
        ColEnd => ColEnd,
        RowStart => RowStart,
        RowEnd => RowEnd,
        K11 => K11,
        K12 => K12,
        K13 => K13,
        K21 => K21,
        K22 => K22,
        K23 => K23,
        K31 => K31,
        K32 => K32,
        K33 => K33,
        ROffset => ROffset,
        GOffset => GOffset,
        BOffset => BOffset,
        ClampMin => ClampMin,
        ClipMax => ClipMax,
        K11_2 => K11_2,
        K12_2 => K12_2,
        K13_2 => K13_2,
        K21_2 => K21_2,
        K22_2 => K22_2,
        K23_2 => K23_2,
        K31_2 => K31_2,
        K32_2 => K32_2,
        K33_2 => K33_2,
        ROffset_2 => ROffset_2,
        GOffset_2 => GOffset_2,
        BOffset_2 => BOffset_2,
        ClampMin_2 => ClampMin_2,
        ClipMax_2 => ClipMax_2,
        stream_in_hresampled_dout => stream_in_hresampled_dout,
        stream_in_hresampled_empty_n => stream_in_hresampled_empty_n,
        stream_in_hresampled_read => v_csc_core_U0_stream_in_hresampled_read,
        stream_in_hresampled_num_data_valid => stream_in_hresampled_num_data_valid,
        stream_in_hresampled_fifo_cap => stream_in_hresampled_fifo_cap,
        stream_csc_din => v_csc_core_U0_stream_csc_din,
        stream_csc_full_n => stream_csc_full_n,
        stream_csc_write => v_csc_core_U0_stream_csc_write,
        stream_csc_num_data_valid => v_csc_core_U0_stream_csc_num_data_valid,
        stream_csc_fifo_cap => v_csc_core_U0_stream_csc_fifo_cap);

    v_hcresampler_core_1_U0 : component bd_197a_csc_0_v_hcresampler_core_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => v_hcresampler_core_1_U0_ap_start,
        start_full_n => start_for_MultiPixStream2AXIvideo_U0_full_n,
        ap_done => v_hcresampler_core_1_U0_ap_done,
        ap_continue => v_hcresampler_core_1_U0_ap_continue,
        ap_idle => v_hcresampler_core_1_U0_ap_idle,
        ap_ready => v_hcresampler_core_1_U0_ap_ready,
        start_out => v_hcresampler_core_1_U0_start_out,
        start_write => v_hcresampler_core_1_U0_start_write,
        height => height,
        width => width,
        p_read => cond64_loc_channel_dout,
        stream_csc_dout => stream_csc_dout,
        stream_csc_empty_n => stream_csc_empty_n,
        stream_csc_read => v_hcresampler_core_1_U0_stream_csc_read,
        stream_csc_num_data_valid => stream_csc_num_data_valid,
        stream_csc_fifo_cap => stream_csc_fifo_cap,
        stream_out_hresampled_din => v_hcresampler_core_1_U0_stream_out_hresampled_din,
        stream_out_hresampled_full_n => stream_out_hresampled_full_n,
        stream_out_hresampled_write => v_hcresampler_core_1_U0_stream_out_hresampled_write,
        stream_out_hresampled_num_data_valid => v_hcresampler_core_1_U0_stream_out_hresampled_num_data_valid,
        stream_out_hresampled_fifo_cap => v_hcresampler_core_1_U0_stream_out_hresampled_fifo_cap);

    MultiPixStream2AXIvideo_U0 : component bd_197a_csc_0_MultiPixStream2AXIvideo
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => MultiPixStream2AXIvideo_U0_ap_start,
        ap_done => MultiPixStream2AXIvideo_U0_ap_done,
        ap_continue => MultiPixStream2AXIvideo_U0_ap_continue,
        ap_idle => MultiPixStream2AXIvideo_U0_ap_idle,
        ap_ready => MultiPixStream2AXIvideo_U0_ap_ready,
        height => height,
        width => width,
        OutVideoFormat => OutVideoFormat,
        stream_out_hresampled_dout => stream_out_hresampled_dout,
        stream_out_hresampled_empty_n => stream_out_hresampled_empty_n,
        stream_out_hresampled_read => MultiPixStream2AXIvideo_U0_stream_out_hresampled_read,
        stream_out_hresampled_num_data_valid => stream_out_hresampled_num_data_valid,
        stream_out_hresampled_fifo_cap => stream_out_hresampled_fifo_cap,
        m_axis_video_TDATA => MultiPixStream2AXIvideo_U0_m_axis_video_TDATA,
        m_axis_video_TVALID => MultiPixStream2AXIvideo_U0_m_axis_video_TVALID,
        m_axis_video_TREADY => m_axis_video_TREADY,
        m_axis_video_TKEEP => MultiPixStream2AXIvideo_U0_m_axis_video_TKEEP,
        m_axis_video_TSTRB => MultiPixStream2AXIvideo_U0_m_axis_video_TSTRB,
        m_axis_video_TUSER => MultiPixStream2AXIvideo_U0_m_axis_video_TUSER,
        m_axis_video_TLAST => MultiPixStream2AXIvideo_U0_m_axis_video_TLAST,
        m_axis_video_TID => MultiPixStream2AXIvideo_U0_m_axis_video_TID,
        m_axis_video_TDEST => MultiPixStream2AXIvideo_U0_m_axis_video_TDEST);

    cond_loc_channel_U : component bd_197a_csc_0_fifo_w1_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_entry_proc_1_U0_ap_return_0,
        if_full_n => cond_loc_channel_full_n,
        if_write => ap_channel_done_cond_loc_channel,
        if_dout => cond_loc_channel_dout,
        if_empty_n => cond_loc_channel_empty_n,
        if_read => v_hcresampler_core_U0_ap_ready,
        if_num_data_valid => cond_loc_channel_num_data_valid,
        if_fifo_cap => cond_loc_channel_fifo_cap);

    cond64_loc_channel_U : component bd_197a_csc_0_fifo_w1_d4_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_entry_proc_1_U0_ap_return_1,
        if_full_n => cond64_loc_channel_full_n,
        if_write => ap_channel_done_cond64_loc_channel,
        if_dout => cond64_loc_channel_dout,
        if_empty_n => cond64_loc_channel_empty_n,
        if_read => v_hcresampler_core_1_U0_ap_ready,
        if_num_data_valid => cond64_loc_channel_num_data_valid,
        if_fifo_cap => cond64_loc_channel_fifo_cap);

    stream_in_U : component bd_197a_csc_0_fifo_w48_d16_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2MultiPixStream_U0_stream_in_din,
        if_full_n => stream_in_full_n,
        if_write => AXIvideo2MultiPixStream_U0_stream_in_write,
        if_dout => stream_in_dout,
        if_empty_n => stream_in_empty_n,
        if_read => v_hcresampler_core_U0_stream_in_read,
        if_num_data_valid => stream_in_num_data_valid,
        if_fifo_cap => stream_in_fifo_cap);

    stream_in_hresampled_U : component bd_197a_csc_0_fifo_w48_d16_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => v_hcresampler_core_U0_stream_in_hresampled_din,
        if_full_n => stream_in_hresampled_full_n,
        if_write => v_hcresampler_core_U0_stream_in_hresampled_write,
        if_dout => stream_in_hresampled_dout,
        if_empty_n => stream_in_hresampled_empty_n,
        if_read => v_csc_core_U0_stream_in_hresampled_read,
        if_num_data_valid => stream_in_hresampled_num_data_valid,
        if_fifo_cap => stream_in_hresampled_fifo_cap);

    stream_csc_U : component bd_197a_csc_0_fifo_w48_d16_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => v_csc_core_U0_stream_csc_din,
        if_full_n => stream_csc_full_n,
        if_write => v_csc_core_U0_stream_csc_write,
        if_dout => stream_csc_dout,
        if_empty_n => stream_csc_empty_n,
        if_read => v_hcresampler_core_1_U0_stream_csc_read,
        if_num_data_valid => stream_csc_num_data_valid,
        if_fifo_cap => stream_csc_fifo_cap);

    stream_out_hresampled_U : component bd_197a_csc_0_fifo_w48_d16_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => v_hcresampler_core_1_U0_stream_out_hresampled_din,
        if_full_n => stream_out_hresampled_full_n,
        if_write => v_hcresampler_core_1_U0_stream_out_hresampled_write,
        if_dout => stream_out_hresampled_dout,
        if_empty_n => stream_out_hresampled_empty_n,
        if_read => MultiPixStream2AXIvideo_U0_stream_out_hresampled_read,
        if_num_data_valid => stream_out_hresampled_num_data_valid,
        if_fifo_cap => stream_out_hresampled_fifo_cap);

    start_for_v_csc_core_U0_U : component bd_197a_csc_0_start_for_v_csc_core_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_v_csc_core_U0_din,
        if_full_n => start_for_v_csc_core_U0_full_n,
        if_write => v_hcresampler_core_U0_start_write,
        if_dout => start_for_v_csc_core_U0_dout,
        if_empty_n => start_for_v_csc_core_U0_empty_n,
        if_read => v_csc_core_U0_ap_ready);

    start_for_MultiPixStream2AXIvideo_U0_U : component bd_197a_csc_0_start_for_MultiPixStream2AXIvideo_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_MultiPixStream2AXIvideo_U0_din,
        if_full_n => start_for_MultiPixStream2AXIvideo_U0_full_n,
        if_write => v_hcresampler_core_1_U0_start_write,
        if_dout => start_for_MultiPixStream2AXIvideo_U0_dout,
        if_empty_n => start_for_MultiPixStream2AXIvideo_U0_empty_n,
        if_read => MultiPixStream2AXIvideo_U0_ap_ready);





    ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready <= ap_sync_AXIvideo2MultiPixStream_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_Block_entry_proc_1_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_Block_entry_proc_1_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_Block_entry_proc_1_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_Block_entry_proc_1_U0_ap_ready <= ap_sync_Block_entry_proc_1_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_cond64_loc_channel_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_cond64_loc_channel <= ap_const_logic_0;
            else
                if (((Block_entry_proc_1_U0_ap_done and Block_entry_proc_1_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_cond64_loc_channel <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_cond64_loc_channel <= ap_sync_channel_write_cond64_loc_channel;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_cond_loc_channel_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_cond_loc_channel <= ap_const_logic_0;
            else
                if (((Block_entry_proc_1_U0_ap_done and Block_entry_proc_1_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_cond_loc_channel <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_cond_loc_channel <= ap_sync_channel_write_cond_loc_channel;
                end if; 
            end if;
        end if;
    end process;

    AXIvideo2MultiPixStream_U0_ap_continue <= ap_const_logic_1;
    AXIvideo2MultiPixStream_U0_ap_start <= ((ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready xor ap_const_logic_1) and ap_start and ap_const_logic_1);
    Block_entry_proc_1_U0_ap_continue <= (ap_sync_channel_write_cond_loc_channel and ap_sync_channel_write_cond64_loc_channel);
    Block_entry_proc_1_U0_ap_start <= ((ap_sync_reg_Block_entry_proc_1_U0_ap_ready xor ap_const_logic_1) and ap_start and ap_const_logic_1);
    MultiPixStream2AXIvideo_U0_ap_continue <= ap_const_logic_1;
    MultiPixStream2AXIvideo_U0_ap_start <= start_for_MultiPixStream2AXIvideo_U0_empty_n;
    ap_channel_done_cond64_loc_channel <= ((ap_sync_reg_channel_write_cond64_loc_channel xor ap_const_logic_1) and Block_entry_proc_1_U0_ap_done);
    ap_channel_done_cond_loc_channel <= ((ap_sync_reg_channel_write_cond_loc_channel xor ap_const_logic_1) and Block_entry_proc_1_U0_ap_done);
    ap_done <= MultiPixStream2AXIvideo_U0_ap_done;
    ap_idle <= (v_hcresampler_core_U0_ap_idle and v_hcresampler_core_1_U0_ap_idle and v_csc_core_U0_ap_idle and (cond64_loc_channel_empty_n xor ap_const_logic_1) and (cond_loc_channel_empty_n xor ap_const_logic_1) and MultiPixStream2AXIvideo_U0_ap_idle and Block_entry_proc_1_U0_ap_idle and AXIvideo2MultiPixStream_U0_ap_idle);
    ap_ready <= ap_sync_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_AXIvideo2MultiPixStream_U0_ap_ready <= (ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready or AXIvideo2MultiPixStream_U0_ap_ready);
    ap_sync_Block_entry_proc_1_U0_ap_ready <= (ap_sync_reg_Block_entry_proc_1_U0_ap_ready or Block_entry_proc_1_U0_ap_ready);
    ap_sync_channel_write_cond64_loc_channel <= ((cond64_loc_channel_full_n and ap_channel_done_cond64_loc_channel) or ap_sync_reg_channel_write_cond64_loc_channel);
    ap_sync_channel_write_cond_loc_channel <= ((cond_loc_channel_full_n and ap_channel_done_cond_loc_channel) or ap_sync_reg_channel_write_cond_loc_channel);
    ap_sync_ready <= (ap_sync_Block_entry_proc_1_U0_ap_ready and ap_sync_AXIvideo2MultiPixStream_U0_ap_ready);
    m_axis_video_TDATA <= MultiPixStream2AXIvideo_U0_m_axis_video_TDATA;
    m_axis_video_TDEST <= MultiPixStream2AXIvideo_U0_m_axis_video_TDEST;
    m_axis_video_TID <= MultiPixStream2AXIvideo_U0_m_axis_video_TID;
    m_axis_video_TKEEP <= MultiPixStream2AXIvideo_U0_m_axis_video_TKEEP;
    m_axis_video_TLAST <= MultiPixStream2AXIvideo_U0_m_axis_video_TLAST;
    m_axis_video_TSTRB <= MultiPixStream2AXIvideo_U0_m_axis_video_TSTRB;
    m_axis_video_TUSER <= MultiPixStream2AXIvideo_U0_m_axis_video_TUSER;
    m_axis_video_TVALID <= MultiPixStream2AXIvideo_U0_m_axis_video_TVALID;
    s_axis_video_TREADY <= AXIvideo2MultiPixStream_U0_s_axis_video_TREADY;
    start_for_MultiPixStream2AXIvideo_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_v_csc_core_U0_din <= (0=>ap_const_logic_1, others=>'-');
    v_csc_core_U0_ap_continue <= ap_const_logic_1;
    v_csc_core_U0_ap_start <= start_for_v_csc_core_U0_empty_n;
    v_csc_core_U0_stream_csc_fifo_cap <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(stream_csc_fifo_cap),5))),32));
    v_csc_core_U0_stream_csc_num_data_valid <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(stream_csc_num_data_valid),5))),32));
    v_hcresampler_core_1_U0_ap_continue <= ap_const_logic_1;
    v_hcresampler_core_1_U0_ap_start <= cond64_loc_channel_empty_n;
    v_hcresampler_core_1_U0_stream_out_hresampled_fifo_cap <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(stream_out_hresampled_fifo_cap),5))),32));
    v_hcresampler_core_1_U0_stream_out_hresampled_num_data_valid <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(stream_out_hresampled_num_data_valid),5))),32));
    v_hcresampler_core_U0_ap_continue <= ap_const_logic_1;
    v_hcresampler_core_U0_ap_start <= cond_loc_channel_empty_n;
    v_hcresampler_core_U0_stream_in_hresampled_fifo_cap <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(stream_in_hresampled_fifo_cap),5))),32));
    v_hcresampler_core_U0_stream_in_hresampled_num_data_valid <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(stream_in_hresampled_num_data_valid),5))),32));
end behav;
