-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bd_197a_csc_0_v_hcresampler_core_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    height : IN STD_LOGIC_VECTOR (15 downto 0);
    width : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_csc_dout : IN STD_LOGIC_VECTOR (47 downto 0);
    stream_csc_empty_n : IN STD_LOGIC;
    stream_csc_read : OUT STD_LOGIC;
    stream_csc_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_csc_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_out_hresampled_din : OUT STD_LOGIC_VECTOR (47 downto 0);
    stream_out_hresampled_full_n : IN STD_LOGIC;
    stream_out_hresampled_write : OUT STD_LOGIC;
    stream_out_hresampled_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    stream_out_hresampled_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of bd_197a_csc_0_v_hcresampler_core_1 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv15_1 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal p_read_3_reg_546 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal loopHeight_reg_576 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal xOffset_fu_237_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xOffset_reg_581 : STD_LOGIC_VECTOR (0 downto 0);
    signal lshr_ln_fu_246_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal lshr_ln_reg_586 : STD_LOGIC_VECTOR (14 downto 0);
    signal loopWidth_fu_260_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal loopWidth_reg_591 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln769_fu_266_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln769_reg_596 : STD_LOGIC_VECTOR (0 downto 0);
    signal pixbuf_y_2_load_reg_607 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal pixbuf_y_3_load_reg_612 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_ap_start : STD_LOGIC;
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_ap_done : STD_LOGIC;
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_ap_idle : STD_LOGIC;
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_ap_ready : STD_LOGIC;
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_stream_csc_read : STD_LOGIC;
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_stream_out_hresampled_din : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_stream_out_hresampled_write : STD_LOGIC;
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_11_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_11_out_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_10_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_10_out_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_9_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_9_out_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_8_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_8_out_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_7_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_7_out_o_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_6_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_6_out_o_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_mpix_cr_3_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_mpix_cr_3_out_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_mpix_cr_2_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_mpix_cr_2_out_o_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_mpix_cb_3_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_mpix_cb_3_out_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_mpix_cb_2_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_mpix_cb_2_out_o_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_p_0_0_0_0_0_3782_i_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_p_0_0_0_0_0_3782_i_out_o_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_p_0_0_0_0_0509_3778_i_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_p_0_0_0_0_0509_3778_i_out_o_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_p_0_0_0_0_0_2774_i_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_p_0_0_0_0_0_2774_i_out_o_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_p_0_0_0_0_0509_2770_i_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_p_0_0_0_0_0509_2770_i_out_o_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_5_0_0_0_load755_i_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_5_0_0_0_load755_i_out_o_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_4_0_0_0_load753_i_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_4_0_0_0_load753_i_out_o_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_3_0_0_0_load751_i_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_3_0_0_0_load751_i_out_o_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_2_0_0_0_load749_i_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_2_0_0_0_load749_i_out_o_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_1_0_0_0_load747_i_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_1_0_0_0_load747_i_out_o_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_0_0_0_0_load745_i_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_0_0_0_0_load745_i_out_o_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal pixbuf_y_3_fu_144 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixbuf_y_2_fu_140 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixbuf_y_1_fu_136 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixbuf_y_fu_132 : STD_LOGIC_VECTOR (7 downto 0);
    signal mpix_cr_fu_124 : STD_LOGIC_VECTOR (7 downto 0);
    signal mpix_cb_fu_116 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0_0_0_3783_lcssa844_i_fu_104 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0_0_0509_3779_lcssa841_i_fu_100 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0_0_0_2775_lcssa838_i_fu_96 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0_0_0509_2771_lcssa835_i_fu_92 : STD_LOGIC_VECTOR (7 downto 0);
    signal inpix_0_5_0_0_0_load756_lcssa815_i_fu_80 : STD_LOGIC_VECTOR (7 downto 0);
    signal inpix_0_4_0_0_0_load754_lcssa812_i_fu_76 : STD_LOGIC_VECTOR (7 downto 0);
    signal inpix_0_3_0_0_0_load752_lcssa809_i_fu_72 : STD_LOGIC_VECTOR (7 downto 0);
    signal inpix_0_2_0_0_0_load750_lcssa806_i_fu_68 : STD_LOGIC_VECTOR (7 downto 0);
    signal inpix_0_1_0_0_0_load748_lcssa803_i_fu_64 : STD_LOGIC_VECTOR (7 downto 0);
    signal inpix_0_0_0_0_0_load746_lcssa800_i_fu_60 : STD_LOGIC_VECTOR (7 downto 0);
    signal y_2_fu_56 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal add_ln767_fu_284_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln767_fu_279_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_0_0_0_0_0517758_lcssa818_i_fu_84 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln738_3_fu_363_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal p_0_3_0_0_0760_lcssa821_i_fu_88 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln738_2_fu_357_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0_0_0509_1_3788_lcssa847_i_fu_108 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln738_1_fu_351_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge_lcssa850_i_fu_112 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln738_fu_345_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal mpix_cb_1_fu_120 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal mpix_cr_1_fu_128 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal pixbuf_y_4_fu_148 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal pixbuf_y_5_fu_152 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal zext_ln765_fu_256_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln730_fu_242_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln767_fu_275_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component bd_197a_csc_0_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        stream_csc_dout : IN STD_LOGIC_VECTOR (47 downto 0);
        stream_csc_empty_n : IN STD_LOGIC;
        stream_csc_read : OUT STD_LOGIC;
        stream_csc_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_csc_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_out_hresampled_din : OUT STD_LOGIC_VECTOR (47 downto 0);
        stream_out_hresampled_full_n : IN STD_LOGIC;
        stream_out_hresampled_write : OUT STD_LOGIC;
        stream_out_hresampled_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        stream_out_hresampled_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        pixbuf_y_5 : IN STD_LOGIC_VECTOR (7 downto 0);
        pixbuf_y_4 : IN STD_LOGIC_VECTOR (7 downto 0);
        pixbuf_y_3 : IN STD_LOGIC_VECTOR (7 downto 0);
        pixbuf_y_2 : IN STD_LOGIC_VECTOR (7 downto 0);
        mpix_cr_1 : IN STD_LOGIC_VECTOR (7 downto 0);
        mpix_cb_1 : IN STD_LOGIC_VECTOR (7 downto 0);
        storemerge_lcssa850_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0509_1_3788_lcssa847_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_3_0_0_0760_lcssa821_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0517758_lcssa818_i : IN STD_LOGIC_VECTOR (7 downto 0);
        loopWidth : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read : IN STD_LOGIC_VECTOR (0 downto 0);
        zext_ln730 : IN STD_LOGIC_VECTOR (0 downto 0);
        lshr_ln : IN STD_LOGIC_VECTOR (14 downto 0);
        pixbuf_y_11_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        pixbuf_y_11_out_ap_vld : OUT STD_LOGIC;
        pixbuf_y_10_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        pixbuf_y_10_out_ap_vld : OUT STD_LOGIC;
        pixbuf_y_9_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        pixbuf_y_9_out_ap_vld : OUT STD_LOGIC;
        pixbuf_y_8_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        pixbuf_y_8_out_ap_vld : OUT STD_LOGIC;
        pixbuf_y_7_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        pixbuf_y_7_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        pixbuf_y_7_out_o_ap_vld : OUT STD_LOGIC;
        pixbuf_y_6_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        pixbuf_y_6_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        pixbuf_y_6_out_o_ap_vld : OUT STD_LOGIC;
        mpix_cr_3_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        mpix_cr_3_out_ap_vld : OUT STD_LOGIC;
        mpix_cr_2_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        mpix_cr_2_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        mpix_cr_2_out_o_ap_vld : OUT STD_LOGIC;
        mpix_cb_3_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        mpix_cb_3_out_ap_vld : OUT STD_LOGIC;
        mpix_cb_2_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        mpix_cb_2_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        mpix_cb_2_out_o_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0_0_3782_i_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0_3782_i_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0_3782_i_out_o_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0_0509_3778_i_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0509_3778_i_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0509_3778_i_out_o_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0_0_2774_i_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0_2774_i_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0_2774_i_out_o_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0_0509_2770_i_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0509_2770_i_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0509_2770_i_out_o_ap_vld : OUT STD_LOGIC;
        inpix_0_5_0_0_0_load755_i_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        inpix_0_5_0_0_0_load755_i_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        inpix_0_5_0_0_0_load755_i_out_o_ap_vld : OUT STD_LOGIC;
        inpix_0_4_0_0_0_load753_i_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        inpix_0_4_0_0_0_load753_i_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        inpix_0_4_0_0_0_load753_i_out_o_ap_vld : OUT STD_LOGIC;
        inpix_0_3_0_0_0_load751_i_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        inpix_0_3_0_0_0_load751_i_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        inpix_0_3_0_0_0_load751_i_out_o_ap_vld : OUT STD_LOGIC;
        inpix_0_2_0_0_0_load749_i_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        inpix_0_2_0_0_0_load749_i_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        inpix_0_2_0_0_0_load749_i_out_o_ap_vld : OUT STD_LOGIC;
        inpix_0_1_0_0_0_load747_i_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        inpix_0_1_0_0_0_load747_i_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        inpix_0_1_0_0_0_load747_i_out_o_ap_vld : OUT STD_LOGIC;
        inpix_0_0_0_0_0_load745_i_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        inpix_0_0_0_0_0_load745_i_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        inpix_0_0_0_0_0_load745_i_out_o_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190 : component bd_197a_csc_0_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_ap_start,
        ap_done => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_ap_done,
        ap_idle => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_ap_idle,
        ap_ready => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_ap_ready,
        stream_csc_dout => stream_csc_dout,
        stream_csc_empty_n => stream_csc_empty_n,
        stream_csc_read => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_stream_csc_read,
        stream_csc_num_data_valid => ap_const_lv5_0,
        stream_csc_fifo_cap => ap_const_lv5_0,
        stream_out_hresampled_din => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_stream_out_hresampled_din,
        stream_out_hresampled_full_n => stream_out_hresampled_full_n,
        stream_out_hresampled_write => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_stream_out_hresampled_write,
        stream_out_hresampled_num_data_valid => stream_out_hresampled_num_data_valid,
        stream_out_hresampled_fifo_cap => stream_out_hresampled_fifo_cap,
        pixbuf_y_5 => pixbuf_y_5_fu_152,
        pixbuf_y_4 => pixbuf_y_4_fu_148,
        pixbuf_y_3 => pixbuf_y_3_load_reg_612,
        pixbuf_y_2 => pixbuf_y_2_load_reg_607,
        mpix_cr_1 => mpix_cr_1_fu_128,
        mpix_cb_1 => mpix_cb_1_fu_120,
        storemerge_lcssa850_i => storemerge_lcssa850_i_fu_112,
        p_0_0_0_0_0509_1_3788_lcssa847_i => p_0_0_0_0_0509_1_3788_lcssa847_i_fu_108,
        p_0_3_0_0_0760_lcssa821_i => p_0_3_0_0_0760_lcssa821_i_fu_88,
        p_0_0_0_0_0517758_lcssa818_i => p_0_0_0_0_0517758_lcssa818_i_fu_84,
        loopWidth => loopWidth_reg_591,
        p_read => p_read_3_reg_546,
        zext_ln730 => xOffset_reg_581,
        lshr_ln => lshr_ln_reg_586,
        pixbuf_y_11_out => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_11_out,
        pixbuf_y_11_out_ap_vld => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_11_out_ap_vld,
        pixbuf_y_10_out => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_10_out,
        pixbuf_y_10_out_ap_vld => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_10_out_ap_vld,
        pixbuf_y_9_out => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_9_out,
        pixbuf_y_9_out_ap_vld => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_9_out_ap_vld,
        pixbuf_y_8_out => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_8_out,
        pixbuf_y_8_out_ap_vld => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_8_out_ap_vld,
        pixbuf_y_7_out_i => pixbuf_y_1_fu_136,
        pixbuf_y_7_out_o => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_7_out_o,
        pixbuf_y_7_out_o_ap_vld => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_7_out_o_ap_vld,
        pixbuf_y_6_out_i => pixbuf_y_fu_132,
        pixbuf_y_6_out_o => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_6_out_o,
        pixbuf_y_6_out_o_ap_vld => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_6_out_o_ap_vld,
        mpix_cr_3_out => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_mpix_cr_3_out,
        mpix_cr_3_out_ap_vld => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_mpix_cr_3_out_ap_vld,
        mpix_cr_2_out_i => mpix_cr_fu_124,
        mpix_cr_2_out_o => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_mpix_cr_2_out_o,
        mpix_cr_2_out_o_ap_vld => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_mpix_cr_2_out_o_ap_vld,
        mpix_cb_3_out => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_mpix_cb_3_out,
        mpix_cb_3_out_ap_vld => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_mpix_cb_3_out_ap_vld,
        mpix_cb_2_out_i => mpix_cb_fu_116,
        mpix_cb_2_out_o => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_mpix_cb_2_out_o,
        mpix_cb_2_out_o_ap_vld => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_mpix_cb_2_out_o_ap_vld,
        p_0_0_0_0_0_3782_i_out_i => p_0_0_0_0_0_3783_lcssa844_i_fu_104,
        p_0_0_0_0_0_3782_i_out_o => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_p_0_0_0_0_0_3782_i_out_o,
        p_0_0_0_0_0_3782_i_out_o_ap_vld => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_p_0_0_0_0_0_3782_i_out_o_ap_vld,
        p_0_0_0_0_0509_3778_i_out_i => p_0_0_0_0_0509_3779_lcssa841_i_fu_100,
        p_0_0_0_0_0509_3778_i_out_o => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_p_0_0_0_0_0509_3778_i_out_o,
        p_0_0_0_0_0509_3778_i_out_o_ap_vld => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_p_0_0_0_0_0509_3778_i_out_o_ap_vld,
        p_0_0_0_0_0_2774_i_out_i => p_0_0_0_0_0_2775_lcssa838_i_fu_96,
        p_0_0_0_0_0_2774_i_out_o => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_p_0_0_0_0_0_2774_i_out_o,
        p_0_0_0_0_0_2774_i_out_o_ap_vld => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_p_0_0_0_0_0_2774_i_out_o_ap_vld,
        p_0_0_0_0_0509_2770_i_out_i => p_0_0_0_0_0509_2771_lcssa835_i_fu_92,
        p_0_0_0_0_0509_2770_i_out_o => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_p_0_0_0_0_0509_2770_i_out_o,
        p_0_0_0_0_0509_2770_i_out_o_ap_vld => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_p_0_0_0_0_0509_2770_i_out_o_ap_vld,
        inpix_0_5_0_0_0_load755_i_out_i => inpix_0_5_0_0_0_load756_lcssa815_i_fu_80,
        inpix_0_5_0_0_0_load755_i_out_o => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_5_0_0_0_load755_i_out_o,
        inpix_0_5_0_0_0_load755_i_out_o_ap_vld => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_5_0_0_0_load755_i_out_o_ap_vld,
        inpix_0_4_0_0_0_load753_i_out_i => inpix_0_4_0_0_0_load754_lcssa812_i_fu_76,
        inpix_0_4_0_0_0_load753_i_out_o => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_4_0_0_0_load753_i_out_o,
        inpix_0_4_0_0_0_load753_i_out_o_ap_vld => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_4_0_0_0_load753_i_out_o_ap_vld,
        inpix_0_3_0_0_0_load751_i_out_i => inpix_0_3_0_0_0_load752_lcssa809_i_fu_72,
        inpix_0_3_0_0_0_load751_i_out_o => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_3_0_0_0_load751_i_out_o,
        inpix_0_3_0_0_0_load751_i_out_o_ap_vld => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_3_0_0_0_load751_i_out_o_ap_vld,
        inpix_0_2_0_0_0_load749_i_out_i => inpix_0_2_0_0_0_load750_lcssa806_i_fu_68,
        inpix_0_2_0_0_0_load749_i_out_o => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_2_0_0_0_load749_i_out_o,
        inpix_0_2_0_0_0_load749_i_out_o_ap_vld => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_2_0_0_0_load749_i_out_o_ap_vld,
        inpix_0_1_0_0_0_load747_i_out_i => inpix_0_1_0_0_0_load748_lcssa803_i_fu_64,
        inpix_0_1_0_0_0_load747_i_out_o => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_1_0_0_0_load747_i_out_o,
        inpix_0_1_0_0_0_load747_i_out_o_ap_vld => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_1_0_0_0_load747_i_out_o_ap_vld,
        inpix_0_0_0_0_0_load745_i_out_i => inpix_0_0_0_0_0_load746_lcssa800_i_fu_60,
        inpix_0_0_0_0_0_load745_i_out_o => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_0_0_0_0_load745_i_out_o,
        inpix_0_0_0_0_0_load745_i_out_o_ap_vld => grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_0_0_0_0_load745_i_out_o_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln767_fu_279_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_ap_ready = ap_const_logic_1)) then 
                    grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    y_2_fu_56_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_2_fu_56 <= ap_const_lv15_0;
            elsif (((icmp_ln767_fu_279_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                y_2_fu_56 <= add_ln767_fu_284_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                icmp_ln769_reg_596 <= icmp_ln769_fu_266_p2;
                loopHeight_reg_576 <= height;
                loopWidth_reg_591 <= loopWidth_fu_260_p2;
                lshr_ln_reg_586 <= width(15 downto 1);
                xOffset_reg_581 <= xOffset_fu_237_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_0_0_0_0_load745_i_out_o_ap_vld = ap_const_logic_1))) then
                inpix_0_0_0_0_0_load746_lcssa800_i_fu_60 <= grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_0_0_0_0_load745_i_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_1_0_0_0_load747_i_out_o_ap_vld = ap_const_logic_1))) then
                inpix_0_1_0_0_0_load748_lcssa803_i_fu_64 <= grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_1_0_0_0_load747_i_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_2_0_0_0_load749_i_out_o_ap_vld = ap_const_logic_1))) then
                inpix_0_2_0_0_0_load750_lcssa806_i_fu_68 <= grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_2_0_0_0_load749_i_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_3_0_0_0_load751_i_out_o_ap_vld = ap_const_logic_1))) then
                inpix_0_3_0_0_0_load752_lcssa809_i_fu_72 <= grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_3_0_0_0_load751_i_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_4_0_0_0_load753_i_out_o_ap_vld = ap_const_logic_1))) then
                inpix_0_4_0_0_0_load754_lcssa812_i_fu_76 <= grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_4_0_0_0_load753_i_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_5_0_0_0_load755_i_out_o_ap_vld = ap_const_logic_1))) then
                inpix_0_5_0_0_0_load756_lcssa815_i_fu_80 <= grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_inpix_0_5_0_0_0_load755_i_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                mpix_cb_1_fu_120 <= grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_mpix_cb_3_out;
                mpix_cr_1_fu_128 <= grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_mpix_cr_3_out;
                p_0_0_0_0_0509_1_3788_lcssa847_i_fu_108 <= select_ln738_1_fu_351_p3;
                p_0_0_0_0_0517758_lcssa818_i_fu_84 <= select_ln738_3_fu_363_p3;
                p_0_3_0_0_0760_lcssa821_i_fu_88 <= select_ln738_2_fu_357_p3;
                pixbuf_y_4_fu_148 <= grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_10_out;
                pixbuf_y_5_fu_152 <= grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_11_out;
                storemerge_lcssa850_i_fu_112 <= select_ln738_fu_345_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_mpix_cb_2_out_o_ap_vld = ap_const_logic_1))) then
                mpix_cb_fu_116 <= grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_mpix_cb_2_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_mpix_cr_2_out_o_ap_vld = ap_const_logic_1))) then
                mpix_cr_fu_124 <= grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_mpix_cr_2_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_p_0_0_0_0_0509_2770_i_out_o_ap_vld = ap_const_logic_1))) then
                p_0_0_0_0_0509_2771_lcssa835_i_fu_92 <= grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_p_0_0_0_0_0509_2770_i_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_p_0_0_0_0_0509_3778_i_out_o_ap_vld = ap_const_logic_1))) then
                p_0_0_0_0_0509_3779_lcssa841_i_fu_100 <= grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_p_0_0_0_0_0509_3778_i_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_p_0_0_0_0_0_2774_i_out_o_ap_vld = ap_const_logic_1))) then
                p_0_0_0_0_0_2775_lcssa838_i_fu_96 <= grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_p_0_0_0_0_0_2774_i_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_p_0_0_0_0_0_3782_i_out_o_ap_vld = ap_const_logic_1))) then
                p_0_0_0_0_0_3783_lcssa844_i_fu_104 <= grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_p_0_0_0_0_0_3782_i_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                p_read_3_reg_546 <= p_read;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_7_out_o_ap_vld = ap_const_logic_1))) then
                pixbuf_y_1_fu_136 <= grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_7_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_8_out_ap_vld = ap_const_logic_1))) then
                pixbuf_y_2_fu_140 <= grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_8_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                pixbuf_y_2_load_reg_607 <= pixbuf_y_2_fu_140;
                pixbuf_y_3_load_reg_612 <= pixbuf_y_3_fu_144;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_9_out_ap_vld = ap_const_logic_1))) then
                pixbuf_y_3_fu_144 <= grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_9_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_6_out_o_ap_vld = ap_const_logic_1))) then
                pixbuf_y_fu_132 <= grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_6_out_o;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state3, grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_ap_done, ap_CS_fsm_state5, icmp_ln767_fu_279_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln767_fu_279_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_ln767_fu_284_p2 <= std_logic_vector(unsigned(y_2_fu_56) + unsigned(ap_const_lv15_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_ap_done)
    begin
        if ((grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state3, icmp_ln767_fu_279_p2)
    begin
        if (((icmp_ln767_fu_279_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_ap_start <= grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_ap_start_reg;
    icmp_ln767_fu_279_p2 <= "1" when (signed(zext_ln767_fu_275_p1) < signed(loopHeight_reg_576)) else "0";
    icmp_ln769_fu_266_p2 <= "1" when (signed(loopWidth_fu_260_p2) > signed(ap_const_lv16_0)) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state3, icmp_ln767_fu_279_p2)
    begin
        if (((icmp_ln767_fu_279_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    loopWidth_fu_260_p2 <= std_logic_vector(unsigned(zext_ln765_fu_256_p1) + unsigned(zext_ln730_fu_242_p1));
    lshr_ln_fu_246_p4 <= width(15 downto 1);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln738_1_fu_351_p3 <= 
        grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_mpix_cb_3_out when (icmp_ln769_reg_596(0) = '1') else 
        p_0_0_0_0_0509_1_3788_lcssa847_i_fu_108;
    select_ln738_2_fu_357_p3 <= 
        grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_11_out when (icmp_ln769_reg_596(0) = '1') else 
        p_0_3_0_0_0760_lcssa821_i_fu_88;
    select_ln738_3_fu_363_p3 <= 
        grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_pixbuf_y_10_out when (icmp_ln769_reg_596(0) = '1') else 
        p_0_0_0_0_0517758_lcssa818_i_fu_84;
    select_ln738_fu_345_p3 <= 
        grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_mpix_cr_3_out when (icmp_ln769_reg_596(0) = '1') else 
        storemerge_lcssa850_i_fu_112;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    stream_csc_read <= grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_stream_csc_read;
    stream_out_hresampled_din <= grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_stream_out_hresampled_din;
    stream_out_hresampled_write <= grp_v_hcresampler_core_1_Pipeline_VITIS_LOOP_769_2_fu_190_stream_out_hresampled_write;
    xOffset_fu_237_p2 <= (p_read_3_reg_546 xor ap_const_lv1_1);
    zext_ln730_fu_242_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xOffset_fu_237_p2),16));
    zext_ln765_fu_256_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_246_p4),16));
    zext_ln767_fu_275_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_2_fu_56),16));
end behav;
