-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_frmbuf_wr_0_0_AXIvideo2MultiPixStream is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    s_axis_video_TDATA : IN STD_LOGIC_VECTOR (47 downto 0);
    s_axis_video_TVALID : IN STD_LOGIC;
    s_axis_video_TREADY : OUT STD_LOGIC;
    s_axis_video_TKEEP : IN STD_LOGIC_VECTOR (5 downto 0);
    s_axis_video_TSTRB : IN STD_LOGIC_VECTOR (5 downto 0);
    s_axis_video_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    img_din : OUT STD_LOGIC_VECTOR (47 downto 0);
    img_full_n : IN STD_LOGIC;
    img_write : OUT STD_LOGIC;
    img_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    img_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    Height_val : IN STD_LOGIC_VECTOR (10 downto 0);
    WidthIn_val : IN STD_LOGIC_VECTOR (10 downto 0);
    colorFormat_val : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of design_1_v_frmbuf_wr_0_0_AXIvideo2MultiPixStream is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_done : STD_LOGIC;
    signal colorFormat_val_read_reg_469 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_reg_unsigned_short_s_fu_225_ap_return : STD_LOGIC_VECTOR (10 downto 0);
    signal rows_reg_474 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln7_fu_278_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln7_reg_482 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln326_fu_288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln326_reg_487 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln407_fu_294_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln407_reg_492 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln407_1_fu_318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln407_1_reg_503 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal and_ln407_fu_374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln407_reg_514 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_start : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_idle : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_ready : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_s_axis_video_TREADY : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_axi_last_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_axi_last_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_axi_data_promoted429_out : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_axi_data_promoted429_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_start : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_done : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_idle : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_ready : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_img_din : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_img_write : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_s_axis_video_TREADY : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_p_4_0_0_0187424_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_p_4_0_0_0187424_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_p_0_0_0_0179415_out : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_p_0_0_0_0179415_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_ap_start : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_ap_done : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_ap_idle : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_ap_ready : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_s_axis_video_TREADY : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_p_4_0_0_0187423_lcssa446_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_p_4_0_0_0187423_lcssa446_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_p_0_0_0_0179416_lcssa430_out : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_p_0_0_0_0179416_lcssa430_out_ap_vld : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_225_ap_start : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_225_ap_done : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_225_ap_idle : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_225_ap_ready : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_225_ap_ce : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_231_ap_start : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_231_ap_done : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_231_ap_idle : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_231_ap_ready : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_231_ap_ce : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_231_ap_return : STD_LOGIC_VECTOR (10 downto 0);
    signal p_4_0_0_0187423_lcssa448_reg_126 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal sof_reg_136 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call17 : BOOLEAN;
    signal axi_last_loc_fu_104 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_0_0_0_0179416_lcssa432_fu_88 : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln322_fu_303_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal p_4_0_0_0187423_lcssa446_loc_fu_92 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_reg_unsigned_short_s_fu_225_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm_state2 : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_231_ap_start_reg : STD_LOGIC := '0';
    signal i_fu_84 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal i_2_fu_308_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_frmbuf_wr_0_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_axis_video_TVALID : IN STD_LOGIC;
        s_axis_video_TDATA : IN STD_LOGIC_VECTOR (47 downto 0);
        s_axis_video_TREADY : OUT STD_LOGIC;
        s_axis_video_TKEEP : IN STD_LOGIC_VECTOR (5 downto 0);
        s_axis_video_TSTRB : IN STD_LOGIC_VECTOR (5 downto 0);
        s_axis_video_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        axi_last_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        axi_last_out_ap_vld : OUT STD_LOGIC;
        axi_data_promoted429_out : OUT STD_LOGIC_VECTOR (47 downto 0);
        axi_data_promoted429_out_ap_vld : OUT STD_LOGIC );
    end component;


    component design_1_v_frmbuf_wr_0_0_AXIvideo2MultiPixStream_Pipeline_loop_width IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_axis_video_TVALID : IN STD_LOGIC;
        img_din : OUT STD_LOGIC_VECTOR (47 downto 0);
        img_full_n : IN STD_LOGIC;
        img_write : OUT STD_LOGIC;
        img_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        img_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        p_4_0_0_0187423_lcssa448 : IN STD_LOGIC_VECTOR (0 downto 0);
        p_0_0_0_0179416_lcssa432 : IN STD_LOGIC_VECTOR (47 downto 0);
        sof_2 : IN STD_LOGIC_VECTOR (0 downto 0);
        colorFormat_val : IN STD_LOGIC_VECTOR (2 downto 0);
        trunc_ln7 : IN STD_LOGIC_VECTOR (9 downto 0);
        s_axis_video_TDATA : IN STD_LOGIC_VECTOR (47 downto 0);
        s_axis_video_TREADY : OUT STD_LOGIC;
        s_axis_video_TKEEP : IN STD_LOGIC_VECTOR (5 downto 0);
        s_axis_video_TSTRB : IN STD_LOGIC_VECTOR (5 downto 0);
        s_axis_video_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        p_4_0_0_0187424_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        p_4_0_0_0187424_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0179415_out : OUT STD_LOGIC_VECTOR (47 downto 0);
        p_0_0_0_0179415_out_ap_vld : OUT STD_LOGIC );
    end component;


    component design_1_v_frmbuf_wr_0_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_axis_video_TVALID : IN STD_LOGIC;
        p_4_0_0_0187424_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        p_0_0_0_0179415_reload : IN STD_LOGIC_VECTOR (47 downto 0);
        and_ln407 : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TDATA : IN STD_LOGIC_VECTOR (47 downto 0);
        s_axis_video_TREADY : OUT STD_LOGIC;
        s_axis_video_TKEEP : IN STD_LOGIC_VECTOR (5 downto 0);
        s_axis_video_TSTRB : IN STD_LOGIC_VECTOR (5 downto 0);
        s_axis_video_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        p_4_0_0_0187423_lcssa446_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        p_4_0_0_0187423_lcssa446_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0179416_lcssa430_out : OUT STD_LOGIC_VECTOR (47 downto 0);
        p_0_0_0_0179416_lcssa430_out_ap_vld : OUT STD_LOGIC );
    end component;


    component design_1_v_frmbuf_wr_0_0_reg_unsigned_short_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_ce : IN STD_LOGIC;
        d : IN STD_LOGIC_VECTOR (10 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;



begin
    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148 : component design_1_v_frmbuf_wr_0_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_start,
        ap_done => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_done,
        ap_idle => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_idle,
        ap_ready => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_ready,
        s_axis_video_TVALID => s_axis_video_TVALID,
        s_axis_video_TDATA => s_axis_video_TDATA,
        s_axis_video_TREADY => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_s_axis_video_TREADY,
        s_axis_video_TKEEP => s_axis_video_TKEEP,
        s_axis_video_TSTRB => s_axis_video_TSTRB,
        s_axis_video_TUSER => s_axis_video_TUSER,
        s_axis_video_TLAST => s_axis_video_TLAST,
        s_axis_video_TID => s_axis_video_TID,
        s_axis_video_TDEST => s_axis_video_TDEST,
        axi_last_out => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_axi_last_out,
        axi_last_out_ap_vld => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_axi_last_out_ap_vld,
        axi_data_promoted429_out => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_axi_data_promoted429_out,
        axi_data_promoted429_out_ap_vld => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_axi_data_promoted429_out_ap_vld);

    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168 : component design_1_v_frmbuf_wr_0_0_AXIvideo2MultiPixStream_Pipeline_loop_width
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_start,
        ap_done => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_done,
        ap_idle => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_idle,
        ap_ready => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_ready,
        s_axis_video_TVALID => s_axis_video_TVALID,
        img_din => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_img_din,
        img_full_n => img_full_n,
        img_write => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_img_write,
        img_num_data_valid => ap_const_lv3_0,
        img_fifo_cap => ap_const_lv3_0,
        p_4_0_0_0187423_lcssa448 => p_4_0_0_0187423_lcssa448_reg_126,
        p_0_0_0_0179416_lcssa432 => p_0_0_0_0179416_lcssa432_fu_88,
        sof_2 => sof_reg_136,
        colorFormat_val => colorFormat_val_read_reg_469,
        trunc_ln7 => trunc_ln7_reg_482,
        s_axis_video_TDATA => s_axis_video_TDATA,
        s_axis_video_TREADY => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_s_axis_video_TREADY,
        s_axis_video_TKEEP => s_axis_video_TKEEP,
        s_axis_video_TSTRB => s_axis_video_TSTRB,
        s_axis_video_TUSER => s_axis_video_TUSER,
        s_axis_video_TLAST => s_axis_video_TLAST,
        s_axis_video_TID => s_axis_video_TID,
        s_axis_video_TDEST => s_axis_video_TDEST,
        p_4_0_0_0187424_out => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_p_4_0_0_0187424_out,
        p_4_0_0_0187424_out_ap_vld => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_p_4_0_0_0187424_out_ap_vld,
        p_0_0_0_0179415_out => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_p_0_0_0_0179415_out,
        p_0_0_0_0179415_out_ap_vld => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_p_0_0_0_0179415_out_ap_vld);

    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197 : component design_1_v_frmbuf_wr_0_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_ap_start,
        ap_done => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_ap_done,
        ap_idle => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_ap_idle,
        ap_ready => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_ap_ready,
        s_axis_video_TVALID => s_axis_video_TVALID,
        p_4_0_0_0187424_reload => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_p_4_0_0_0187424_out,
        p_0_0_0_0179415_reload => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_p_0_0_0_0179415_out,
        and_ln407 => and_ln407_reg_514,
        s_axis_video_TDATA => s_axis_video_TDATA,
        s_axis_video_TREADY => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_s_axis_video_TREADY,
        s_axis_video_TKEEP => s_axis_video_TKEEP,
        s_axis_video_TSTRB => s_axis_video_TSTRB,
        s_axis_video_TUSER => s_axis_video_TUSER,
        s_axis_video_TLAST => s_axis_video_TLAST,
        s_axis_video_TID => s_axis_video_TID,
        s_axis_video_TDEST => s_axis_video_TDEST,
        p_4_0_0_0187423_lcssa446_out => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_p_4_0_0_0187423_lcssa446_out,
        p_4_0_0_0187423_lcssa446_out_ap_vld => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_p_4_0_0_0187423_lcssa446_out_ap_vld,
        p_0_0_0_0179416_lcssa430_out => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_p_0_0_0_0179416_lcssa430_out,
        p_0_0_0_0179416_lcssa430_out_ap_vld => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_p_0_0_0_0179416_lcssa430_out_ap_vld);

    grp_reg_unsigned_short_s_fu_225 : component design_1_v_frmbuf_wr_0_0_reg_unsigned_short_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_reg_unsigned_short_s_fu_225_ap_start,
        ap_done => grp_reg_unsigned_short_s_fu_225_ap_done,
        ap_idle => grp_reg_unsigned_short_s_fu_225_ap_idle,
        ap_ready => grp_reg_unsigned_short_s_fu_225_ap_ready,
        ap_ce => grp_reg_unsigned_short_s_fu_225_ap_ce,
        d => Height_val,
        ap_return => grp_reg_unsigned_short_s_fu_225_ap_return);

    grp_reg_unsigned_short_s_fu_231 : component design_1_v_frmbuf_wr_0_0_reg_unsigned_short_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_reg_unsigned_short_s_fu_231_ap_start,
        ap_done => grp_reg_unsigned_short_s_fu_231_ap_done,
        ap_idle => grp_reg_unsigned_short_s_fu_231_ap_idle,
        ap_ready => grp_reg_unsigned_short_s_fu_231_ap_ready,
        ap_ce => grp_reg_unsigned_short_s_fu_231_ap_ce,
        d => WidthIn_val,
        ap_return => grp_reg_unsigned_short_s_fu_231_ap_return);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln322_fu_303_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_ap_ready = ap_const_logic_1)) then 
                    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state1_ignore_call17) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_ready = ap_const_logic_1)) then 
                    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln322_fu_303_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_ready = ap_const_logic_1)) then 
                    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_reg_unsigned_short_s_fu_225_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_reg_unsigned_short_s_fu_225_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_NS_fsm_state2))) then 
                    grp_reg_unsigned_short_s_fu_225_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_reg_unsigned_short_s_fu_225_ap_ready = ap_const_logic_1)) then 
                    grp_reg_unsigned_short_s_fu_225_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_reg_unsigned_short_s_fu_231_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_reg_unsigned_short_s_fu_231_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_NS_fsm_state2))) then 
                    grp_reg_unsigned_short_s_fu_231_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_reg_unsigned_short_s_fu_231_ap_ready = ap_const_logic_1)) then 
                    grp_reg_unsigned_short_s_fu_231_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_fu_84 <= ap_const_lv11_0;
            elsif (((icmp_ln322_fu_303_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                i_fu_84 <= i_2_fu_308_p2;
            end if; 
        end if;
    end process;

    p_0_0_0_0179416_lcssa432_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_p_0_0_0_0179416_lcssa430_out_ap_vld = ap_const_logic_1))) then 
                p_0_0_0_0179416_lcssa432_fu_88 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_p_0_0_0_0179416_lcssa430_out;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_axi_data_promoted429_out_ap_vld = ap_const_logic_1))) then 
                p_0_0_0_0179416_lcssa432_fu_88 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_axi_data_promoted429_out;
            end if; 
        end if;
    end process;

    p_4_0_0_0187423_lcssa448_reg_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                p_4_0_0_0187423_lcssa448_reg_126 <= p_4_0_0_0187423_lcssa446_loc_fu_92;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                p_4_0_0_0187423_lcssa448_reg_126 <= axi_last_loc_fu_104;
            end if; 
        end if;
    end process;

    sof_reg_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                sof_reg_136 <= and_ln407_1_reg_503;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                sof_reg_136 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                and_ln407_1_reg_503 <= and_ln407_1_fu_318_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                and_ln407_reg_514 <= and_ln407_fu_374_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_axi_last_out_ap_vld = ap_const_logic_1))) then
                axi_last_loc_fu_104 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_axi_last_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                colorFormat_val_read_reg_469 <= colorFormat_val;
                icmp_ln326_reg_487 <= icmp_ln326_fu_288_p2;
                rows_reg_474 <= grp_reg_unsigned_short_s_fu_225_ap_return;
                trunc_ln7_reg_482 <= grp_reg_unsigned_short_s_fu_231_ap_return(10 downto 1);
                xor_ln407_reg_492 <= xor_ln407_fu_294_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_p_4_0_0_0187423_lcssa446_out_ap_vld = ap_const_logic_1))) then
                p_4_0_0_0187423_lcssa446_loc_fu_92 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_p_4_0_0_0187423_lcssa446_out;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_done, ap_CS_fsm_state4, grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_done, grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_ap_done, icmp_ln322_fu_303_p2, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln322_fu_303_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    and_ln407_1_fu_318_p2 <= (xor_ln407_reg_492 and sof_reg_136);
    and_ln407_fu_374_p2 <= (icmp_ln326_reg_487 and grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_p_4_0_0_0187424_out);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_NS_fsm_state2 <= ap_NS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_done)
    begin
        if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_done)
    begin
        if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_ap_done)
    begin
        if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call17_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call17 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state4, icmp_ln322_fu_303_p2)
    begin
        if (((icmp_ln322_fu_303_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_ap_start <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_ap_start_reg;
    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_start <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_start_reg;
    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_start <= grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_ap_start_reg;

    grp_reg_unsigned_short_s_fu_225_ap_ce_assign_proc : process(ap_CS_fsm_state2, grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_done, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            grp_reg_unsigned_short_s_fu_225_ap_ce <= ap_const_logic_1;
        else 
            grp_reg_unsigned_short_s_fu_225_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_reg_unsigned_short_s_fu_225_ap_start <= grp_reg_unsigned_short_s_fu_225_ap_start_reg;

    grp_reg_unsigned_short_s_fu_231_ap_ce_assign_proc : process(ap_CS_fsm_state2, grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_done, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            grp_reg_unsigned_short_s_fu_231_ap_ce <= ap_const_logic_1;
        else 
            grp_reg_unsigned_short_s_fu_231_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_reg_unsigned_short_s_fu_231_ap_start <= grp_reg_unsigned_short_s_fu_231_ap_start_reg;
    i_2_fu_308_p2 <= std_logic_vector(unsigned(i_fu_84) + unsigned(ap_const_lv11_1));
    icmp_ln322_fu_303_p2 <= "1" when (i_fu_84 = rows_reg_474) else "0";
    icmp_ln326_fu_288_p2 <= "0" when (trunc_ln7_fu_278_p4 = ap_const_lv10_0) else "1";
    img_din <= grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_img_din;
    img_write <= grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_img_write;

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state4, icmp_ln322_fu_303_p2)
    begin
        if (((icmp_ln322_fu_303_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;


    s_axis_video_TREADY_assign_proc : process(ap_CS_fsm_state2, grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_s_axis_video_TREADY, grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_s_axis_video_TREADY, grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_s_axis_video_TREADY, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            s_axis_video_TREADY <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_197_s_axis_video_TREADY;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            s_axis_video_TREADY <= grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_168_s_axis_video_TREADY;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            s_axis_video_TREADY <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_148_s_axis_video_TREADY;
        else 
            s_axis_video_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln7_fu_278_p4 <= grp_reg_unsigned_short_s_fu_231_ap_return(10 downto 1);
    xor_ln407_fu_294_p2 <= (icmp_ln326_fu_288_p2 xor ap_const_lv1_1);
end behav;
