set_property SRC_FILE_INFO {cfile:C:/TFG_Vivado/vivado/axu2cga_trd.srcs/constrs_1/new/gpio.xdc rfile:../../../axu2cga_trd.srcs/constrs_1/new/gpio.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:C:/TFG_Vivado/vivado/axu2cga_trd.srcs/constrs_1/new/mipi.xdc rfile:../../../axu2cga_trd.srcs/constrs_1/new/mipi.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:C:/TFG_Vivado/vivado/axu2cga_trd.srcs/constrs_1/new/system.xdc rfile:../../../axu2cga_trd.srcs/constrs_1/new/system.xdc id:3} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA13 [get_ports {btns_tri_i[0]}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE14 [get_ports {btns_tri_i[1]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE15 [get_ports {btns_tri_i[2]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG14 [get_ports {btns_tri_i[3]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W13	 [get_ports {leds_tri_o[0]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y12	 [get_ports {leds_tri_o[1]}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA12 [get_ports {leds_tri_o[2]}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB13 [get_ports {leds_tri_o[3]}]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH14 [get_ports {cam0_gpio[0]}]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH13 [get_ports cam0_i2c_scl_io]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE13 [get_ports cam0_i2c_sda_io]
set_property src_info {type:XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD15 [get_ports {cam1_gpio[0]}]
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD14 [get_ports cam1_i2c_scl_io]
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC13 [get_ports cam1_i2c_sda_io]
set_property src_info {type:XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB11 [get_ports pl_ref_clk]
set_property src_info {type:XDC file:3 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W12 [get_ports {fan_tri_o[0]}]
