-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_863_5 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    img_dout : IN STD_LOGIC_VECTOR (47 downto 0);
    img_empty_n : IN STD_LOGIC;
    img_read : OUT STD_LOGIC;
    img_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    img_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    bytePlanes_plane0_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    bytePlanes_plane0_full_n : IN STD_LOGIC;
    bytePlanes_plane0_write : OUT STD_LOGIC;
    bytePlanes_plane0_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    bytePlanes_plane0_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    pix_7 : IN STD_LOGIC_VECTOR (7 downto 0);
    pix_6 : IN STD_LOGIC_VECTOR (7 downto 0);
    pix_5 : IN STD_LOGIC_VECTOR (7 downto 0);
    pix_4 : IN STD_LOGIC_VECTOR (7 downto 0);
    loopWidth_1 : IN STD_LOGIC_VECTOR (9 downto 0);
    icmp_ln851 : IN STD_LOGIC_VECTOR (0 downto 0);
    icmp_ln868_2 : IN STD_LOGIC_VECTOR (0 downto 0);
    icmp9 : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln868 : IN STD_LOGIC_VECTOR (10 downto 0);
    icmp_ln868 : IN STD_LOGIC_VECTOR (0 downto 0);
    pix_19_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    pix_19_out_ap_vld : OUT STD_LOGIC;
    pix_18_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    pix_18_out_ap_vld : OUT STD_LOGIC;
    pix_17_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    pix_17_out_ap_vld : OUT STD_LOGIC;
    pix_16_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    pix_16_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_863_5 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal icmp_ln863_reg_638 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln868_reg_642 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op55_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage1_iter0_grp1 : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal or_ln868_2_reg_650 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op76_read_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage3_iter0_grp3 : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal bytePlanes_plane0_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage1_grp1 : BOOLEAN;
    signal img_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_grp2 : BOOLEAN;
    signal or_ln868_1_reg_646 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage3_grp3 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal or_ln868_3_reg_654 : STD_LOGIC_VECTOR (0 downto 0);
    signal pix_45_reg_193 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_44_reg_203 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_43_reg_213 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_42_reg_223 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_69_reg_233 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_68_reg_244 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_67_reg_255 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_66_reg_266 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_87_reg_277 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_86_reg_288 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_85_reg_299 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_84_reg_310 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_93_reg_321 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_92_reg_332 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_91_reg_343 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_90_reg_354 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln863_fu_435_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op86_read_state5 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal or_ln868_fu_457_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln868_1_fu_463_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln868_2_fu_469_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln868_3_fu_475_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_pix_45_phi_fu_196_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_45_reg_193 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage1_11001_grp1 : BOOLEAN;
    signal ap_phi_mux_pix_44_phi_fu_206_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_44_reg_203 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_pix_43_phi_fu_216_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_43_reg_213 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_pix_42_phi_fu_226_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_79_fu_502_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_42_reg_223 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_pix_69_phi_fu_236_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_69_reg_233 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_predicate_op65_read_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage2_iter0_grp2 : BOOLEAN;
    signal ap_block_pp0_stage2_11001_grp2 : BOOLEAN;
    signal ap_phi_mux_pix_68_phi_fu_247_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_68_reg_244 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_pix_67_phi_fu_258_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_67_reg_255 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_pix_66_phi_fu_269_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_80_fu_507_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_66_reg_266 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_pix_87_phi_fu_280_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_87_reg_277 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage3_11001_grp3 : BOOLEAN;
    signal ap_phi_mux_pix_86_phi_fu_291_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_86_reg_288 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_pix_85_phi_fu_302_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_85_reg_299 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_pix_84_phi_fu_313_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_82_fu_512_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_84_reg_310 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_pix_93_phi_fu_324_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_93_reg_321 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_93_reg_321 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage3_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage3_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage3_subdone_grp0 : BOOLEAN;
    signal ap_phi_mux_pix_92_phi_fu_335_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_92_reg_332 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_92_reg_332 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_pix_91_phi_fu_346_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_91_reg_343 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_91_reg_343 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_pix_90_phi_fu_357_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_88_fu_517_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_90_reg_354 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_90_reg_354 : STD_LOGIC_VECTOR (7 downto 0);
    signal x_1_fu_100 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal x_3_fu_441_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_x : STD_LOGIC_VECTOR (9 downto 0);
    signal pix_16_fu_104 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal pix_17_fu_108 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal pix_18_fu_112 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal pix_19_fu_116 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_block_pp0_stage1_01001_grp1 : BOOLEAN;
    signal zext_ln865_fu_447_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln868_1_fu_451_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_524 : BOOLEAN;
    signal ap_condition_529 : BOOLEAN;
    signal ap_condition_229 : BOOLEAN;
    signal ap_condition_260 : BOOLEAN;
    signal ap_condition_278 : BOOLEAN;
    signal ap_condition_293 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_frmbuf_wr_0_0_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component design_1_v_frmbuf_wr_0_0_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage3_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage3_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then 
                        ap_block_pp0_stage3_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp0)) then 
                        ap_block_pp0_stage3_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_pix_90_reg_354_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                if ((ap_const_boolean_1 = ap_condition_524)) then 
                    ap_phi_reg_pp0_iter1_pix_90_reg_354 <= ap_phi_mux_pix_84_phi_fu_313_p4;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp0))) then 
                    ap_phi_reg_pp0_iter1_pix_90_reg_354 <= ap_phi_reg_pp0_iter0_pix_90_reg_354;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_pix_91_reg_343_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                if ((ap_const_boolean_1 = ap_condition_524)) then 
                    ap_phi_reg_pp0_iter1_pix_91_reg_343 <= ap_phi_mux_pix_85_phi_fu_302_p4;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp0))) then 
                    ap_phi_reg_pp0_iter1_pix_91_reg_343 <= ap_phi_reg_pp0_iter0_pix_91_reg_343;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_pix_92_reg_332_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                if ((ap_const_boolean_1 = ap_condition_524)) then 
                    ap_phi_reg_pp0_iter1_pix_92_reg_332 <= ap_phi_mux_pix_86_phi_fu_291_p4;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp0))) then 
                    ap_phi_reg_pp0_iter1_pix_92_reg_332 <= ap_phi_reg_pp0_iter0_pix_92_reg_332;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_pix_93_reg_321_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                if ((ap_const_boolean_1 = ap_condition_524)) then 
                    ap_phi_reg_pp0_iter1_pix_93_reg_321 <= ap_phi_mux_pix_87_phi_fu_280_p4;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp0))) then 
                    ap_phi_reg_pp0_iter1_pix_93_reg_321 <= ap_phi_reg_pp0_iter0_pix_93_reg_321;
                end if;
            end if; 
        end if;
    end process;

    pix_16_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if ((ap_const_boolean_1 = ap_condition_529)) then 
                    pix_16_fu_104 <= pix_4;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    pix_16_fu_104 <= ap_phi_mux_pix_90_phi_fu_357_p4;
                end if;
            end if; 
        end if;
    end process;

    pix_17_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if ((ap_const_boolean_1 = ap_condition_529)) then 
                    pix_17_fu_108 <= pix_5;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    pix_17_fu_108 <= ap_phi_mux_pix_91_phi_fu_346_p4;
                end if;
            end if; 
        end if;
    end process;

    pix_18_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if ((ap_const_boolean_1 = ap_condition_529)) then 
                    pix_18_fu_112 <= pix_6;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    pix_18_fu_112 <= ap_phi_mux_pix_92_phi_fu_335_p4;
                end if;
            end if; 
        end if;
    end process;

    pix_19_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if ((ap_const_boolean_1 = ap_condition_529)) then 
                    pix_19_fu_116 <= pix_7;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    pix_19_fu_116 <= ap_phi_mux_pix_93_phi_fu_324_p4;
                end if;
            end if; 
        end if;
    end process;

    pix_42_reg_223_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_229)) then
                if (((or_ln868_reg_642 = ap_const_lv1_0) and (icmp_ln863_reg_638 = ap_const_lv1_0))) then 
                    pix_42_reg_223 <= pix_16_fu_104;
                elsif (((or_ln868_reg_642 = ap_const_lv1_1) and (icmp_ln863_reg_638 = ap_const_lv1_0))) then 
                    pix_42_reg_223 <= pix_79_fu_502_p1;
                elsif (not((icmp_ln863_reg_638 = ap_const_lv1_1))) then 
                    pix_42_reg_223 <= ap_phi_reg_pp0_iter0_pix_42_reg_223;
                end if;
            end if; 
        end if;
    end process;

    pix_43_reg_213_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_229)) then
                if (((or_ln868_reg_642 = ap_const_lv1_0) and (icmp_ln863_reg_638 = ap_const_lv1_0))) then 
                    pix_43_reg_213 <= pix_17_fu_108;
                elsif (((or_ln868_reg_642 = ap_const_lv1_1) and (icmp_ln863_reg_638 = ap_const_lv1_0))) then 
                    pix_43_reg_213 <= img_dout(15 downto 8);
                elsif (not((icmp_ln863_reg_638 = ap_const_lv1_1))) then 
                    pix_43_reg_213 <= ap_phi_reg_pp0_iter0_pix_43_reg_213;
                end if;
            end if; 
        end if;
    end process;

    pix_44_reg_203_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_229)) then
                if (((or_ln868_reg_642 = ap_const_lv1_0) and (icmp_ln863_reg_638 = ap_const_lv1_0))) then 
                    pix_44_reg_203 <= pix_18_fu_112;
                elsif (((or_ln868_reg_642 = ap_const_lv1_1) and (icmp_ln863_reg_638 = ap_const_lv1_0))) then 
                    pix_44_reg_203 <= img_dout(31 downto 24);
                elsif (not((icmp_ln863_reg_638 = ap_const_lv1_1))) then 
                    pix_44_reg_203 <= ap_phi_reg_pp0_iter0_pix_44_reg_203;
                end if;
            end if; 
        end if;
    end process;

    pix_45_reg_193_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_229)) then
                if (((or_ln868_reg_642 = ap_const_lv1_0) and (icmp_ln863_reg_638 = ap_const_lv1_0))) then 
                    pix_45_reg_193 <= pix_19_fu_116;
                elsif (((or_ln868_reg_642 = ap_const_lv1_1) and (icmp_ln863_reg_638 = ap_const_lv1_0))) then 
                    pix_45_reg_193 <= img_dout(39 downto 32);
                elsif (not((icmp_ln863_reg_638 = ap_const_lv1_1))) then 
                    pix_45_reg_193 <= ap_phi_reg_pp0_iter0_pix_45_reg_193;
                end if;
            end if; 
        end if;
    end process;

    pix_66_reg_266_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_260)) then
                if (((icmp_ln863_reg_638 = ap_const_lv1_0) and (or_ln868_1_reg_646 = ap_const_lv1_1))) then 
                    pix_66_reg_266 <= pix_80_fu_507_p1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    pix_66_reg_266 <= ap_phi_reg_pp0_iter0_pix_66_reg_266;
                end if;
            end if; 
        end if;
    end process;

    pix_67_reg_255_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_260)) then
                if (((icmp_ln863_reg_638 = ap_const_lv1_0) and (or_ln868_1_reg_646 = ap_const_lv1_1))) then 
                    pix_67_reg_255 <= img_dout(15 downto 8);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    pix_67_reg_255 <= ap_phi_reg_pp0_iter0_pix_67_reg_255;
                end if;
            end if; 
        end if;
    end process;

    pix_68_reg_244_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_260)) then
                if (((icmp_ln863_reg_638 = ap_const_lv1_0) and (or_ln868_1_reg_646 = ap_const_lv1_1))) then 
                    pix_68_reg_244 <= img_dout(31 downto 24);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    pix_68_reg_244 <= ap_phi_reg_pp0_iter0_pix_68_reg_244;
                end if;
            end if; 
        end if;
    end process;

    pix_69_reg_233_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_260)) then
                if (((icmp_ln863_reg_638 = ap_const_lv1_0) and (or_ln868_1_reg_646 = ap_const_lv1_1))) then 
                    pix_69_reg_233 <= img_dout(39 downto 32);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    pix_69_reg_233 <= ap_phi_reg_pp0_iter0_pix_69_reg_233;
                end if;
            end if; 
        end if;
    end process;

    pix_84_reg_310_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_278)) then
                if (((or_ln868_2_reg_650 = ap_const_lv1_1) and (icmp_ln863_reg_638 = ap_const_lv1_0))) then 
                    pix_84_reg_310 <= pix_82_fu_512_p1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    pix_84_reg_310 <= ap_phi_reg_pp0_iter0_pix_84_reg_310;
                end if;
            end if; 
        end if;
    end process;

    pix_85_reg_299_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_278)) then
                if (((or_ln868_2_reg_650 = ap_const_lv1_1) and (icmp_ln863_reg_638 = ap_const_lv1_0))) then 
                    pix_85_reg_299 <= img_dout(15 downto 8);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    pix_85_reg_299 <= ap_phi_reg_pp0_iter0_pix_85_reg_299;
                end if;
            end if; 
        end if;
    end process;

    pix_86_reg_288_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_278)) then
                if (((or_ln868_2_reg_650 = ap_const_lv1_1) and (icmp_ln863_reg_638 = ap_const_lv1_0))) then 
                    pix_86_reg_288 <= img_dout(31 downto 24);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    pix_86_reg_288 <= ap_phi_reg_pp0_iter0_pix_86_reg_288;
                end if;
            end if; 
        end if;
    end process;

    pix_87_reg_277_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_278)) then
                if (((or_ln868_2_reg_650 = ap_const_lv1_1) and (icmp_ln863_reg_638 = ap_const_lv1_0))) then 
                    pix_87_reg_277 <= img_dout(39 downto 32);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    pix_87_reg_277 <= ap_phi_reg_pp0_iter0_pix_87_reg_277;
                end if;
            end if; 
        end if;
    end process;

    pix_90_reg_354_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_293)) then
                if (((icmp_ln863_reg_638 = ap_const_lv1_0) and (or_ln868_3_reg_654 = ap_const_lv1_1))) then 
                    pix_90_reg_354 <= pix_88_fu_517_p1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    pix_90_reg_354 <= ap_phi_reg_pp0_iter1_pix_90_reg_354;
                end if;
            end if; 
        end if;
    end process;

    pix_91_reg_343_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_293)) then
                if (((icmp_ln863_reg_638 = ap_const_lv1_0) and (or_ln868_3_reg_654 = ap_const_lv1_1))) then 
                    pix_91_reg_343 <= img_dout(15 downto 8);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    pix_91_reg_343 <= ap_phi_reg_pp0_iter1_pix_91_reg_343;
                end if;
            end if; 
        end if;
    end process;

    pix_92_reg_332_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_293)) then
                if (((icmp_ln863_reg_638 = ap_const_lv1_0) and (or_ln868_3_reg_654 = ap_const_lv1_1))) then 
                    pix_92_reg_332 <= img_dout(31 downto 24);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    pix_92_reg_332 <= ap_phi_reg_pp0_iter1_pix_92_reg_332;
                end if;
            end if; 
        end if;
    end process;

    pix_93_reg_321_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_293)) then
                if (((icmp_ln863_reg_638 = ap_const_lv1_0) and (or_ln868_3_reg_654 = ap_const_lv1_1))) then 
                    pix_93_reg_321 <= img_dout(39 downto 32);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    pix_93_reg_321 <= ap_phi_reg_pp0_iter1_pix_93_reg_321;
                end if;
            end if; 
        end if;
    end process;

    x_1_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln863_fu_435_p2 = ap_const_lv1_0))) then 
                    x_1_fu_100 <= x_3_fu_441_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    x_1_fu_100 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1) and (icmp_ln863_reg_638 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (or_ln868_1_reg_646 = ap_const_lv1_0))) then
                ap_phi_reg_pp0_iter0_pix_66_reg_266 <= ap_phi_mux_pix_42_phi_fu_226_p4;
                ap_phi_reg_pp0_iter0_pix_67_reg_255 <= ap_phi_mux_pix_43_phi_fu_216_p4;
                ap_phi_reg_pp0_iter0_pix_68_reg_244 <= ap_phi_mux_pix_44_phi_fu_206_p4;
                ap_phi_reg_pp0_iter0_pix_69_reg_233 <= ap_phi_mux_pix_45_phi_fu_196_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((or_ln868_2_reg_650 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp2) and (icmp_ln863_reg_638 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                ap_phi_reg_pp0_iter0_pix_84_reg_310 <= ap_phi_mux_pix_66_phi_fu_269_p4;
                ap_phi_reg_pp0_iter0_pix_85_reg_299 <= ap_phi_mux_pix_67_phi_fu_258_p4;
                ap_phi_reg_pp0_iter0_pix_86_reg_288 <= ap_phi_mux_pix_68_phi_fu_247_p4;
                ap_phi_reg_pp0_iter0_pix_87_reg_277 <= ap_phi_mux_pix_69_phi_fu_236_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln863_reg_638 <= icmp_ln863_fu_435_p2;
                or_ln868_1_reg_646 <= or_ln868_1_fu_463_p2;
                or_ln868_2_reg_650 <= or_ln868_2_fu_469_p2;
                or_ln868_3_reg_654 <= or_ln868_3_fu_475_p2;
                or_ln868_reg_642 <= or_ln868_fu_457_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_idle_pp0, ap_block_pp0_stage1_subdone, ap_condition_exit_pp0_iter0_stage1, ap_block_pp0_stage3_subdone, ap_block_pp0_stage0_subdone, ap_block_pp0_stage2_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_idle_pp0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state5_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state5_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, bytePlanes_plane0_full_n, ap_block_state2_pp0_stage1_iter0_grp1, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage1_01001_grp1 <= (((bytePlanes_plane0_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp1)));
    end process;


    ap_block_pp0_stage1_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, bytePlanes_plane0_full_n, ap_block_state2_pp0_stage1_iter0_grp1, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage1_11001_grp1 <= (((bytePlanes_plane0_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp1)));
    end process;

        ap_block_pp0_stage1_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, bytePlanes_plane0_full_n, ap_block_state2_pp0_stage1_iter0_grp1, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage1_subdone <= (((bytePlanes_plane0_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp1)));
    end process;


    ap_block_pp0_stage2_11001_grp2_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state3_pp0_stage2_iter0_grp2)
    begin
                ap_block_pp0_stage2_11001_grp2 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0_grp2));
    end process;

        ap_block_pp0_stage2_grp2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state3_pp0_stage2_iter0_grp2)
    begin
                ap_block_pp0_stage2_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0_grp2));
    end process;

        ap_block_pp0_stage3_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_11001_grp3_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state4_pp0_stage3_iter0_grp3)
    begin
                ap_block_pp0_stage3_11001_grp3 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0_grp3));
    end process;

        ap_block_pp0_stage3_grp3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state4_pp0_stage3_iter0_grp3)
    begin
                ap_block_pp0_stage3_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0_grp3));
    end process;

        ap_block_pp0_stage3_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage1_iter0_grp1_assign_proc : process(img_empty_n, ap_predicate_op55_read_state2)
    begin
                ap_block_state2_pp0_stage1_iter0_grp1 <= ((ap_predicate_op55_read_state2 = ap_const_boolean_1) and (img_empty_n = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage2_iter0_grp2_assign_proc : process(img_empty_n, ap_predicate_op65_read_state3)
    begin
                ap_block_state3_pp0_stage2_iter0_grp2 <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op65_read_state3 = ap_const_boolean_1));
    end process;


    ap_block_state4_pp0_stage3_iter0_grp3_assign_proc : process(img_empty_n, ap_predicate_op76_read_state4)
    begin
                ap_block_state4_pp0_stage3_iter0_grp3 <= ((ap_predicate_op76_read_state4 = ap_const_boolean_1) and (img_empty_n = ap_const_logic_0));
    end process;


    ap_block_state5_pp0_stage0_iter1_assign_proc : process(img_empty_n, ap_predicate_op86_read_state5)
    begin
                ap_block_state5_pp0_stage0_iter1 <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op86_read_state5 = ap_const_boolean_1));
    end process;


    ap_condition_229_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_11001_grp1)
    begin
                ap_condition_229 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1));
    end process;


    ap_condition_260_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001_grp2)
    begin
                ap_condition_260 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2));
    end process;


    ap_condition_278_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001_grp3)
    begin
                ap_condition_278 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3));
    end process;


    ap_condition_293_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
                ap_condition_293 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_524_assign_proc : process(icmp_ln863_reg_638, or_ln868_3_reg_654, ap_block_pp0_stage3_11001_grp3)
    begin
                ap_condition_524 <= ((ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp3) and (icmp_ln863_reg_638 = ap_const_lv1_0) and (or_ln868_3_reg_654 = ap_const_lv1_0));
    end process;


    ap_condition_529_assign_proc : process(ap_loop_init, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
                ap_condition_529 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln863_reg_638, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (icmp_ln863_reg_638 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;

    ap_phi_mux_pix_42_phi_fu_226_p4_assign_proc : process(icmp_ln863_reg_638, or_ln868_reg_642, pix_79_fu_502_p1, ap_phi_reg_pp0_iter0_pix_42_reg_223, pix_16_fu_104)
    begin
        if ((icmp_ln863_reg_638 = ap_const_lv1_0)) then
            if ((or_ln868_reg_642 = ap_const_lv1_0)) then 
                ap_phi_mux_pix_42_phi_fu_226_p4 <= pix_16_fu_104;
            elsif ((or_ln868_reg_642 = ap_const_lv1_1)) then 
                ap_phi_mux_pix_42_phi_fu_226_p4 <= pix_79_fu_502_p1;
            else 
                ap_phi_mux_pix_42_phi_fu_226_p4 <= ap_phi_reg_pp0_iter0_pix_42_reg_223;
            end if;
        else 
            ap_phi_mux_pix_42_phi_fu_226_p4 <= ap_phi_reg_pp0_iter0_pix_42_reg_223;
        end if; 
    end process;


    ap_phi_mux_pix_43_phi_fu_216_p4_assign_proc : process(img_dout, icmp_ln863_reg_638, or_ln868_reg_642, ap_phi_reg_pp0_iter0_pix_43_reg_213, pix_17_fu_108)
    begin
        if ((icmp_ln863_reg_638 = ap_const_lv1_0)) then
            if ((or_ln868_reg_642 = ap_const_lv1_0)) then 
                ap_phi_mux_pix_43_phi_fu_216_p4 <= pix_17_fu_108;
            elsif ((or_ln868_reg_642 = ap_const_lv1_1)) then 
                ap_phi_mux_pix_43_phi_fu_216_p4 <= img_dout(15 downto 8);
            else 
                ap_phi_mux_pix_43_phi_fu_216_p4 <= ap_phi_reg_pp0_iter0_pix_43_reg_213;
            end if;
        else 
            ap_phi_mux_pix_43_phi_fu_216_p4 <= ap_phi_reg_pp0_iter0_pix_43_reg_213;
        end if; 
    end process;


    ap_phi_mux_pix_44_phi_fu_206_p4_assign_proc : process(img_dout, icmp_ln863_reg_638, or_ln868_reg_642, ap_phi_reg_pp0_iter0_pix_44_reg_203, pix_18_fu_112)
    begin
        if ((icmp_ln863_reg_638 = ap_const_lv1_0)) then
            if ((or_ln868_reg_642 = ap_const_lv1_0)) then 
                ap_phi_mux_pix_44_phi_fu_206_p4 <= pix_18_fu_112;
            elsif ((or_ln868_reg_642 = ap_const_lv1_1)) then 
                ap_phi_mux_pix_44_phi_fu_206_p4 <= img_dout(31 downto 24);
            else 
                ap_phi_mux_pix_44_phi_fu_206_p4 <= ap_phi_reg_pp0_iter0_pix_44_reg_203;
            end if;
        else 
            ap_phi_mux_pix_44_phi_fu_206_p4 <= ap_phi_reg_pp0_iter0_pix_44_reg_203;
        end if; 
    end process;


    ap_phi_mux_pix_45_phi_fu_196_p4_assign_proc : process(img_dout, icmp_ln863_reg_638, or_ln868_reg_642, ap_phi_reg_pp0_iter0_pix_45_reg_193, pix_19_fu_116)
    begin
        if ((icmp_ln863_reg_638 = ap_const_lv1_0)) then
            if ((or_ln868_reg_642 = ap_const_lv1_0)) then 
                ap_phi_mux_pix_45_phi_fu_196_p4 <= pix_19_fu_116;
            elsif ((or_ln868_reg_642 = ap_const_lv1_1)) then 
                ap_phi_mux_pix_45_phi_fu_196_p4 <= img_dout(39 downto 32);
            else 
                ap_phi_mux_pix_45_phi_fu_196_p4 <= ap_phi_reg_pp0_iter0_pix_45_reg_193;
            end if;
        else 
            ap_phi_mux_pix_45_phi_fu_196_p4 <= ap_phi_reg_pp0_iter0_pix_45_reg_193;
        end if; 
    end process;


    ap_phi_mux_pix_66_phi_fu_269_p4_assign_proc : process(icmp_ln863_reg_638, or_ln868_1_reg_646, pix_80_fu_507_p1, ap_phi_reg_pp0_iter0_pix_66_reg_266)
    begin
        if (((icmp_ln863_reg_638 = ap_const_lv1_0) and (or_ln868_1_reg_646 = ap_const_lv1_1))) then 
            ap_phi_mux_pix_66_phi_fu_269_p4 <= pix_80_fu_507_p1;
        else 
            ap_phi_mux_pix_66_phi_fu_269_p4 <= ap_phi_reg_pp0_iter0_pix_66_reg_266;
        end if; 
    end process;


    ap_phi_mux_pix_67_phi_fu_258_p4_assign_proc : process(img_dout, icmp_ln863_reg_638, or_ln868_1_reg_646, ap_phi_reg_pp0_iter0_pix_67_reg_255)
    begin
        if (((icmp_ln863_reg_638 = ap_const_lv1_0) and (or_ln868_1_reg_646 = ap_const_lv1_1))) then 
            ap_phi_mux_pix_67_phi_fu_258_p4 <= img_dout(15 downto 8);
        else 
            ap_phi_mux_pix_67_phi_fu_258_p4 <= ap_phi_reg_pp0_iter0_pix_67_reg_255;
        end if; 
    end process;


    ap_phi_mux_pix_68_phi_fu_247_p4_assign_proc : process(img_dout, icmp_ln863_reg_638, or_ln868_1_reg_646, ap_phi_reg_pp0_iter0_pix_68_reg_244)
    begin
        if (((icmp_ln863_reg_638 = ap_const_lv1_0) and (or_ln868_1_reg_646 = ap_const_lv1_1))) then 
            ap_phi_mux_pix_68_phi_fu_247_p4 <= img_dout(31 downto 24);
        else 
            ap_phi_mux_pix_68_phi_fu_247_p4 <= ap_phi_reg_pp0_iter0_pix_68_reg_244;
        end if; 
    end process;


    ap_phi_mux_pix_69_phi_fu_236_p4_assign_proc : process(img_dout, icmp_ln863_reg_638, or_ln868_1_reg_646, ap_phi_reg_pp0_iter0_pix_69_reg_233)
    begin
        if (((icmp_ln863_reg_638 = ap_const_lv1_0) and (or_ln868_1_reg_646 = ap_const_lv1_1))) then 
            ap_phi_mux_pix_69_phi_fu_236_p4 <= img_dout(39 downto 32);
        else 
            ap_phi_mux_pix_69_phi_fu_236_p4 <= ap_phi_reg_pp0_iter0_pix_69_reg_233;
        end if; 
    end process;


    ap_phi_mux_pix_84_phi_fu_313_p4_assign_proc : process(icmp_ln863_reg_638, or_ln868_2_reg_650, pix_82_fu_512_p1, ap_phi_reg_pp0_iter0_pix_84_reg_310)
    begin
        if (((or_ln868_2_reg_650 = ap_const_lv1_1) and (icmp_ln863_reg_638 = ap_const_lv1_0))) then 
            ap_phi_mux_pix_84_phi_fu_313_p4 <= pix_82_fu_512_p1;
        else 
            ap_phi_mux_pix_84_phi_fu_313_p4 <= ap_phi_reg_pp0_iter0_pix_84_reg_310;
        end if; 
    end process;


    ap_phi_mux_pix_85_phi_fu_302_p4_assign_proc : process(img_dout, icmp_ln863_reg_638, or_ln868_2_reg_650, ap_phi_reg_pp0_iter0_pix_85_reg_299)
    begin
        if (((or_ln868_2_reg_650 = ap_const_lv1_1) and (icmp_ln863_reg_638 = ap_const_lv1_0))) then 
            ap_phi_mux_pix_85_phi_fu_302_p4 <= img_dout(15 downto 8);
        else 
            ap_phi_mux_pix_85_phi_fu_302_p4 <= ap_phi_reg_pp0_iter0_pix_85_reg_299;
        end if; 
    end process;


    ap_phi_mux_pix_86_phi_fu_291_p4_assign_proc : process(img_dout, icmp_ln863_reg_638, or_ln868_2_reg_650, ap_phi_reg_pp0_iter0_pix_86_reg_288)
    begin
        if (((or_ln868_2_reg_650 = ap_const_lv1_1) and (icmp_ln863_reg_638 = ap_const_lv1_0))) then 
            ap_phi_mux_pix_86_phi_fu_291_p4 <= img_dout(31 downto 24);
        else 
            ap_phi_mux_pix_86_phi_fu_291_p4 <= ap_phi_reg_pp0_iter0_pix_86_reg_288;
        end if; 
    end process;


    ap_phi_mux_pix_87_phi_fu_280_p4_assign_proc : process(img_dout, icmp_ln863_reg_638, or_ln868_2_reg_650, ap_phi_reg_pp0_iter0_pix_87_reg_277)
    begin
        if (((or_ln868_2_reg_650 = ap_const_lv1_1) and (icmp_ln863_reg_638 = ap_const_lv1_0))) then 
            ap_phi_mux_pix_87_phi_fu_280_p4 <= img_dout(39 downto 32);
        else 
            ap_phi_mux_pix_87_phi_fu_280_p4 <= ap_phi_reg_pp0_iter0_pix_87_reg_277;
        end if; 
    end process;


    ap_phi_mux_pix_90_phi_fu_357_p4_assign_proc : process(icmp_ln863_reg_638, or_ln868_3_reg_654, pix_88_fu_517_p1, ap_phi_reg_pp0_iter1_pix_90_reg_354)
    begin
        if (((icmp_ln863_reg_638 = ap_const_lv1_0) and (or_ln868_3_reg_654 = ap_const_lv1_1))) then 
            ap_phi_mux_pix_90_phi_fu_357_p4 <= pix_88_fu_517_p1;
        else 
            ap_phi_mux_pix_90_phi_fu_357_p4 <= ap_phi_reg_pp0_iter1_pix_90_reg_354;
        end if; 
    end process;


    ap_phi_mux_pix_91_phi_fu_346_p4_assign_proc : process(img_dout, icmp_ln863_reg_638, or_ln868_3_reg_654, ap_phi_reg_pp0_iter1_pix_91_reg_343)
    begin
        if (((icmp_ln863_reg_638 = ap_const_lv1_0) and (or_ln868_3_reg_654 = ap_const_lv1_1))) then 
            ap_phi_mux_pix_91_phi_fu_346_p4 <= img_dout(15 downto 8);
        else 
            ap_phi_mux_pix_91_phi_fu_346_p4 <= ap_phi_reg_pp0_iter1_pix_91_reg_343;
        end if; 
    end process;


    ap_phi_mux_pix_92_phi_fu_335_p4_assign_proc : process(img_dout, icmp_ln863_reg_638, or_ln868_3_reg_654, ap_phi_reg_pp0_iter1_pix_92_reg_332)
    begin
        if (((icmp_ln863_reg_638 = ap_const_lv1_0) and (or_ln868_3_reg_654 = ap_const_lv1_1))) then 
            ap_phi_mux_pix_92_phi_fu_335_p4 <= img_dout(31 downto 24);
        else 
            ap_phi_mux_pix_92_phi_fu_335_p4 <= ap_phi_reg_pp0_iter1_pix_92_reg_332;
        end if; 
    end process;


    ap_phi_mux_pix_93_phi_fu_324_p4_assign_proc : process(img_dout, icmp_ln863_reg_638, or_ln868_3_reg_654, ap_phi_reg_pp0_iter1_pix_93_reg_321)
    begin
        if (((icmp_ln863_reg_638 = ap_const_lv1_0) and (or_ln868_3_reg_654 = ap_const_lv1_1))) then 
            ap_phi_mux_pix_93_phi_fu_324_p4 <= img_dout(39 downto 32);
        else 
            ap_phi_mux_pix_93_phi_fu_324_p4 <= ap_phi_reg_pp0_iter1_pix_93_reg_321;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_pix_42_reg_223 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_pix_43_reg_213 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_pix_44_reg_203 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_pix_45_reg_193 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_pix_90_reg_354 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_pix_91_reg_343 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_pix_92_reg_332 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_pix_93_reg_321 <= "XXXXXXXX";

    ap_predicate_op55_read_state2_assign_proc : process(icmp_ln863_reg_638, or_ln868_reg_642)
    begin
                ap_predicate_op55_read_state2 <= ((or_ln868_reg_642 = ap_const_lv1_1) and (icmp_ln863_reg_638 = ap_const_lv1_0));
    end process;


    ap_predicate_op65_read_state3_assign_proc : process(icmp_ln863_reg_638, or_ln868_1_reg_646)
    begin
                ap_predicate_op65_read_state3 <= ((icmp_ln863_reg_638 = ap_const_lv1_0) and (or_ln868_1_reg_646 = ap_const_lv1_1));
    end process;


    ap_predicate_op76_read_state4_assign_proc : process(icmp_ln863_reg_638, or_ln868_2_reg_650)
    begin
                ap_predicate_op76_read_state4 <= ((or_ln868_2_reg_650 = ap_const_lv1_1) and (icmp_ln863_reg_638 = ap_const_lv1_0));
    end process;


    ap_predicate_op86_read_state5_assign_proc : process(icmp_ln863_reg_638, or_ln868_3_reg_654)
    begin
                ap_predicate_op86_read_state5 <= ((icmp_ln863_reg_638 = ap_const_lv1_0) and (or_ln868_3_reg_654 = ap_const_lv1_1));
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_x_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, x_1_fu_100, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_x <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_x <= x_1_fu_100;
        end if; 
    end process;


    bytePlanes_plane0_blk_n_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, bytePlanes_plane0_full_n, ap_block_pp0_stage1_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            bytePlanes_plane0_blk_n <= bytePlanes_plane0_full_n;
        else 
            bytePlanes_plane0_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    bytePlanes_plane0_din <= (((((((((((((((pix_92_reg_332 & pix_93_reg_321) & pix_90_reg_354) & pix_91_reg_343) & pix_86_reg_288) & pix_87_reg_277) & pix_84_reg_310) & pix_85_reg_299) & pix_68_reg_244) & pix_69_reg_233) & pix_66_reg_266) & pix_67_reg_255) & pix_44_reg_203) & pix_45_reg_193) & pix_42_reg_223) & pix_43_reg_213);

    bytePlanes_plane0_write_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            bytePlanes_plane0_write <= ap_const_logic_1;
        else 
            bytePlanes_plane0_write <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln863_fu_435_p2 <= "1" when (ap_sig_allocacmp_x = loopWidth_1) else "0";
    icmp_ln868_1_fu_451_p2 <= "1" when (signed(zext_ln865_fu_447_p1) < signed(sext_ln868)) else "0";

    img_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, img_empty_n, icmp_ln863_reg_638, ap_predicate_op55_read_state2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage3, ap_predicate_op76_read_state4, ap_block_pp0_stage1_grp1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_grp2, or_ln868_1_reg_646, ap_block_pp0_stage3_grp3, ap_block_pp0_stage0, or_ln868_3_reg_654)
    begin
        if ((((ap_predicate_op76_read_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_grp3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_grp2) and (icmp_ln863_reg_638 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (or_ln868_1_reg_646 = ap_const_lv1_1)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (ap_predicate_op55_read_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln863_reg_638 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (or_ln868_3_reg_654 = ap_const_lv1_1)))) then 
            img_blk_n <= img_empty_n;
        else 
            img_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_predicate_op55_read_state2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage3, ap_predicate_op76_read_state4, ap_CS_fsm_pp0_stage2, ap_predicate_op86_read_state5, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001_grp1, ap_predicate_op65_read_state3, ap_block_pp0_stage2_11001_grp2, ap_block_pp0_stage3_11001_grp3)
    begin
        if ((((ap_predicate_op76_read_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp2) and (ap_predicate_op65_read_state3 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1) and (ap_predicate_op55_read_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op86_read_state5 = ap_const_boolean_1)))) then 
            img_read <= ap_const_logic_1;
        else 
            img_read <= ap_const_logic_0;
        end if; 
    end process;

    or_ln868_1_fu_463_p2 <= (icmp_ln868_1_fu_451_p2 or icmp9);
    or_ln868_2_fu_469_p2 <= (icmp_ln868_2 or icmp_ln868_1_fu_451_p2);
    or_ln868_3_fu_475_p2 <= (icmp_ln868_1_fu_451_p2 or icmp_ln851);
    or_ln868_fu_457_p2 <= (icmp_ln868_1_fu_451_p2 or icmp_ln868);
    pix_16_out <= pix_16_fu_104;

    pix_16_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln863_reg_638, ap_loop_exit_ready, ap_block_pp0_stage1_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1) and (icmp_ln863_reg_638 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            pix_16_out_ap_vld <= ap_const_logic_1;
        else 
            pix_16_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    pix_17_out <= pix_17_fu_108;

    pix_17_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln863_reg_638, ap_loop_exit_ready, ap_block_pp0_stage1_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1) and (icmp_ln863_reg_638 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            pix_17_out_ap_vld <= ap_const_logic_1;
        else 
            pix_17_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    pix_18_out <= pix_18_fu_112;

    pix_18_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln863_reg_638, ap_loop_exit_ready, ap_block_pp0_stage1_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1) and (icmp_ln863_reg_638 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            pix_18_out_ap_vld <= ap_const_logic_1;
        else 
            pix_18_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    pix_19_out <= pix_19_fu_116;

    pix_19_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln863_reg_638, ap_loop_exit_ready, ap_block_pp0_stage1_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1) and (icmp_ln863_reg_638 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            pix_19_out_ap_vld <= ap_const_logic_1;
        else 
            pix_19_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    pix_79_fu_502_p1 <= img_dout(8 - 1 downto 0);
    pix_80_fu_507_p1 <= img_dout(8 - 1 downto 0);
    pix_82_fu_512_p1 <= img_dout(8 - 1 downto 0);
    pix_88_fu_517_p1 <= img_dout(8 - 1 downto 0);
    x_3_fu_441_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_x) + unsigned(ap_const_lv10_1));
    zext_ln865_fu_447_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_x),11));
end behav;
