-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_frmbuf_wr_1_0_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1599_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    bytePlanes_plane0_dout : IN STD_LOGIC_VECTOR (127 downto 0);
    bytePlanes_plane0_empty_n : IN STD_LOGIC;
    bytePlanes_plane0_read : OUT STD_LOGIC;
    bytePlanes_plane0_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
    bytePlanes_plane0_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_mm_video_0_AWVALID : OUT STD_LOGIC;
    m_axi_mm_video_0_AWREADY : IN STD_LOGIC;
    m_axi_mm_video_0_AWADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_mm_video_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_mm_video_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_mm_video_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_mm_video_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_mm_video_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_mm_video_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_mm_video_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_mm_video_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_mm_video_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_mm_video_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_mm_video_0_WVALID : OUT STD_LOGIC;
    m_axi_mm_video_0_WREADY : IN STD_LOGIC;
    m_axi_mm_video_0_WDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    m_axi_mm_video_0_WSTRB : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axi_mm_video_0_WLAST : OUT STD_LOGIC;
    m_axi_mm_video_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_mm_video_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_mm_video_0_ARVALID : OUT STD_LOGIC;
    m_axi_mm_video_0_ARREADY : IN STD_LOGIC;
    m_axi_mm_video_0_ARADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_mm_video_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_mm_video_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_mm_video_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_mm_video_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_mm_video_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_mm_video_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_mm_video_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_mm_video_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_mm_video_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_mm_video_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_mm_video_0_RVALID : IN STD_LOGIC;
    m_axi_mm_video_0_RREADY : OUT STD_LOGIC;
    m_axi_mm_video_0_RDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    m_axi_mm_video_0_RLAST : IN STD_LOGIC;
    m_axi_mm_video_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_mm_video_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_mm_video_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_mm_video_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_mm_video_0_BVALID : IN STD_LOGIC;
    m_axi_mm_video_0_BREADY : OUT STD_LOGIC;
    m_axi_mm_video_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_mm_video_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_mm_video_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    loopWidth : IN STD_LOGIC_VECTOR (9 downto 0);
    sext_ln1599 : IN STD_LOGIC_VECTOR (27 downto 0) );
end;


architecture behav of design_1_v_frmbuf_wr_1_0_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1599_1 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln1599_fu_112_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal mm_video_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal bytePlanes_plane0_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal bytePlanes_plane0_read_reg_151 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal x_fu_70 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal add_ln1599_fu_118_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_x_8 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_frmbuf_wr_1_0_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component design_1_v_frmbuf_wr_1_0_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    x_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln1599_fu_112_p2 = ap_const_lv1_0))) then 
                    x_fu_70 <= add_ln1599_fu_118_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_70 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                bytePlanes_plane0_read_reg_151 <= bytePlanes_plane0_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln1599_fu_118_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_x_8) + unsigned(ap_const_lv10_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, bytePlanes_plane0_empty_n)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((bytePlanes_plane0_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, bytePlanes_plane0_empty_n, m_axi_mm_video_0_WREADY)
    begin
                ap_block_pp0_stage0_11001 <= (((m_axi_mm_video_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((bytePlanes_plane0_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, bytePlanes_plane0_empty_n, m_axi_mm_video_0_WREADY)
    begin
                ap_block_pp0_stage0_11001_grp1 <= (((m_axi_mm_video_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((bytePlanes_plane0_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, bytePlanes_plane0_empty_n, m_axi_mm_video_0_WREADY)
    begin
                ap_block_pp0_stage0_subdone <= (((m_axi_mm_video_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((bytePlanes_plane0_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln1599_fu_112_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1599_fu_112_p2 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_x_8_assign_proc : process(ap_CS_fsm_pp0_stage0, x_fu_70, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_x_8 <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_x_8 <= x_fu_70;
        end if; 
    end process;


    bytePlanes_plane0_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, bytePlanes_plane0_empty_n, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bytePlanes_plane0_blk_n <= bytePlanes_plane0_empty_n;
        else 
            bytePlanes_plane0_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    bytePlanes_plane0_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bytePlanes_plane0_read <= ap_const_logic_1;
        else 
            bytePlanes_plane0_read <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln1599_fu_112_p2 <= "1" when (ap_sig_allocacmp_x_8 = loopWidth) else "0";
    m_axi_mm_video_0_ARADDR <= ap_const_lv32_0;
    m_axi_mm_video_0_ARBURST <= ap_const_lv2_0;
    m_axi_mm_video_0_ARCACHE <= ap_const_lv4_0;
    m_axi_mm_video_0_ARID <= ap_const_lv1_0;
    m_axi_mm_video_0_ARLEN <= ap_const_lv32_0;
    m_axi_mm_video_0_ARLOCK <= ap_const_lv2_0;
    m_axi_mm_video_0_ARPROT <= ap_const_lv3_0;
    m_axi_mm_video_0_ARQOS <= ap_const_lv4_0;
    m_axi_mm_video_0_ARREGION <= ap_const_lv4_0;
    m_axi_mm_video_0_ARSIZE <= ap_const_lv3_0;
    m_axi_mm_video_0_ARUSER <= ap_const_lv1_0;
    m_axi_mm_video_0_ARVALID <= ap_const_logic_0;
    m_axi_mm_video_0_AWADDR <= ap_const_lv32_0;
    m_axi_mm_video_0_AWBURST <= ap_const_lv2_0;
    m_axi_mm_video_0_AWCACHE <= ap_const_lv4_0;
    m_axi_mm_video_0_AWID <= ap_const_lv1_0;
    m_axi_mm_video_0_AWLEN <= ap_const_lv32_0;
    m_axi_mm_video_0_AWLOCK <= ap_const_lv2_0;
    m_axi_mm_video_0_AWPROT <= ap_const_lv3_0;
    m_axi_mm_video_0_AWQOS <= ap_const_lv4_0;
    m_axi_mm_video_0_AWREGION <= ap_const_lv4_0;
    m_axi_mm_video_0_AWSIZE <= ap_const_lv3_0;
    m_axi_mm_video_0_AWUSER <= ap_const_lv1_0;
    m_axi_mm_video_0_AWVALID <= ap_const_logic_0;
    m_axi_mm_video_0_BREADY <= ap_const_logic_0;
    m_axi_mm_video_0_RREADY <= ap_const_logic_0;
    m_axi_mm_video_0_WDATA <= bytePlanes_plane0_read_reg_151;
    m_axi_mm_video_0_WID <= ap_const_lv1_0;
    m_axi_mm_video_0_WLAST <= ap_const_logic_0;
    m_axi_mm_video_0_WSTRB <= ap_const_lv16_FFFF;
    m_axi_mm_video_0_WUSER <= ap_const_lv1_0;

    m_axi_mm_video_0_WVALID_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            m_axi_mm_video_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_mm_video_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;


    mm_video_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_mm_video_0_WREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            mm_video_blk_n_W <= m_axi_mm_video_0_WREADY;
        else 
            mm_video_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

end behav;
