# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: c:/TFG_Vivado/vivado/axu2cga_trd.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_0/bd_197a_csc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_197a_csc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/TFG_Vivado/vivado/axu2cga_trd.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_0/bd_197a_csc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_197a_csc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/TFG_Vivado/vivado/axu2cga_trd.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_0/bd_197a_csc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_197a_csc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/TFG_Vivado/vivado/axu2cga_trd.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_1_0/bd_0/ip/ip_0/bd_197a_csc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_197a_csc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
